Repository emundus/v6, pull requests merged in 2018-10, with the labels that each got.

#294 🎁&🎨Theme filter
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: filters, search engine

#296 💾 Updated category names to be URL friendly straight from the DB.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, bugfix

#295 🎁&🎨Theme filter
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Design, filters, search engine

#297 💾 Updated category names to be URL friendly straight from the DB.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: Exports, GesCOF, bugfix

#298 🐛🛠 Removed form + button and made it a div + link
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: bugfix, search engine

#301 Creating div for the theme filter...patchy patch
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: filters, patch

#304 🐛🛠 SQL fixes.
  administrator/components/com_admin/sql/updates/mysql/3.8.12-2018-09-06-em.sql
  administrator/components/com_admin/sql/updates/mysql/3.8.12-2018-09-18-em.sql
  administrator/components/com_admin/sql/updates/mysql/3.8.8-2018-06-26-em.sql
Labels: bugfix, patch

#303 insert searched value in search bar on result page
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: filters

#305 🐛🛠 SQL fixes.
  administrator/components/com_admin/sql/updates/mysql/3.8.12-2018-09-06-em.sql
  administrator/components/com_admin/sql/updates/mysql/3.8.12-2018-09-18-em.sql
  administrator/components/com_admin/sql/updates/mysql/3.8.8-2018-06-26-em.sql
Labels: bugfix, patch

#306 Product PDF forms now open in a new tab and a gitignore has been adde…
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  images/product_pdf/.gitignore
Labels: Exports, patch

#307 🐛🛠 Product PDF forms now open in a new tab and a gitignore has been adde…
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  images/product_pdf/.gitignore
Labels: Exports, GesCOF, bugfix

#311 CCIRS filter page tmpl and an SEF bugfix to the campaigns module.
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_buttons.php
  modules/mod_emundus_campaign/tmpl/default.php
  modules/mod_emundus_campaign/tmpl/default_g5.php
Labels: Fabrik, bugfix, search engine

#312 CCIRS filter page tmpl and an SEF bugfix to the campaigns module.
  administrator/templates/isis/images/joomla.png
  administrator/templates/isis/images/logo.png
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_buttons.php
  modules/mod_emundus_campaign/tmpl/default.php
  modules/mod_emundus_campaign/tmpl/default_g5.php
Labels: Design, Fabrik, Production, bugfix

#315 🐛🛠 & 💬 Fixed a bug in the main language file causing the entire engli…
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
Labels: bugfix, patch

#314 Emergency language patch
  administrator/components/com_admin/sql/updates/mysql/3.8.8-2018-06-26-em.sql
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
Labels: Production, bugfix, patch

#313 🎁 Add link to create a project on search page
  components/com_fabrik/views/list/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default_buttons.php
Labels: search engine

#316 Hesam bugfixes & imporvements.
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  modules/mod_emundus_applications/tmpl/hesam.php
  plugins/fabrik_form/php/scripts/emundus-HESAM-link_user_institution.php
  plugins/user/emundus_welcome_message/emundus_welcome_message.php
  plugins/user/emundus_welcome_message/emundus_welcome_message.xml
Labels: Design, bugfix, enhancement, search engine

#317 HESAM improvements and bugfixes.
  administrator/components/com_admin/sql/updates/mysql/3.8.8-2018-06-26-em.sql
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default_buttons.php
  modules/mod_emundus_applications/tmpl/hesam.php
  plugins/fabrik_form/php/scripts/emundus-HESAM-link_user_institution.php
  plugins/user/emundus_welcome_message/emundus_welcome_message.php
  plugins/user/emundus_welcome_message/emundus_welcome_message.xml
Labels: Design, bugfix, search engine

#318 HESAM improvements and bugfixes.
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default_buttons.php
  modules/mod_emundus_applications/tmpl/hesam.php
  plugins/fabrik_form/php/scripts/emundus-HESAM-link_user_institution.php
  plugins/user/emundus_welcome_message/emundus_welcome_message.php
  plugins/user/emundus_welcome_message/emundus_welcome_message.xml
Labels: Design, Plugin, Production, bugfix, search engine

#319 Ccirs v0.9 and bonus bugfixes.
  administrator/components/com_admin/sql/updates/mysql/3.8.12-2018-10-05-em.sql
  components/com_emundus/controllers/users.php
  components/com_emundus/models/emails.php
  components/com_emundus/models/users.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
  modules/mod_emundus_category_search/language/en-GB/en-GB.mod_emundus_category_search.ini
  modules/mod_emundus_category_search/language/fr-FR/fr-FR.mod_emundus_category_search.ini
  modules/mod_emundus_category_search/mod_emundus_category_search.php
  modules/mod_emundus_category_search/mod_emundus_category_search.xml
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/fullWidth.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: Design, GesCOF, Module, Production, bugfix

#321 CCIRS v0.9, Major bugfixes, and small improvements to HESAM.
  administrator/components/com_admin/sql/updates/mysql/3.8.12-2018-10-05-em.sql
  components/com_emundus/controllers/users.php
  components/com_emundus/models/emails.php
  components/com_emundus/models/users.php
  components/com_emundus/views/messages/tmpl/chat.php
  components/com_emundus/views/messages/tmpl/default.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
  modules/mod_emundus_category_search/language/en-GB/en-GB.mod_emundus_category_search.ini
  modules/mod_emundus_category_search/language/fr-FR/fr-FR.mod_emundus_category_search.ini
  modules/mod_emundus_category_search/mod_emundus_category_search.php
  modules/mod_emundus_category_search/mod_emundus_category_search.xml
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/fullWidth.php
  modules/mod_emundus_cifre_suggestions/tmpl/default.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, Module, Plugin, Production, bugfix, search engine

#325 Modified CCIRS search page frontend to be able to handle date start a…
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Design, bugfix, search engine

#331 🐛🛠 Fixed jQuery selector.
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: bugfix, patch

#330 🐛🛠 Fixed jQuery selector.
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Production, bugfix, patch

#332 CCIRS V1: PDF improvements, GesCOF fixes, and partner & certificate support.
  components/com_emundus/controllers/files.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/fullWidth.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: Exports, GesCOF, Module, bugfix, search engine

#333 Joomla 3.8.13 and final improvements for CCIRS V1
  .idea/workspace.xml
  administrator/components/com_installer/controllers/database.php
  administrator/components/com_installer/controllers/discover.php
  administrator/components/com_joomlaupdate/joomlaupdate.php
  administrator/language/en-GB/en-GB.xml
  administrator/language/en-GB/install.xml
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  administrator/modules/mod_menu/menu.php
  administrator/templates/isis/images/joomla.png
  administrator/templates/isis/images/logo.png
  components/com_contact/controllers/contact.php
  components/com_emundus/controllers/files.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  components/com_tags/controllers/tags.php
  components/com_users/controllers/registration.php
  components/com_users/models/registration.php
  language/en-GB/en-GB.com_users.ini
  language/en-GB/en-GB.xml
  language/en-GB/install.xml
  language/index.html
  libraries/src/Helper/TagsHelper.php
  libraries/src/Version.php
  modules/mod_emundus_category_search/mod_emundus_category_search.xml
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/fullWidth.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: Design, Exports, GesCOF, Joomla!, Module, bugfix, search engine

#336 Added PDF footer and improved margins.
  components/com_emundus/controllers/files.php
  libraries/emundus/pdf.php
Labels: Design, Exports, patch

#335 Added PDF footer and improved margins.
  components/com_emundus/controllers/files.php
  libraries/emundus/pdf.php
Labels: Design, Exports, Production, patch

#337 Pdf date patch
  components/com_emundus/controllers/files.php
Labels: Exports, Production, patch

#338 PDF date encoding patch.
  components/com_emundus/controllers/files.php
Labels: Exports, patch

#339 UGA expert rights fix
  components/com_emundus/controller.php
  plugins/fabrik_form/php/scripts/emundus-UGA-expert_agreement.php
Labels: Exports, bugfix

#340 GesCOF publish tweak
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, enhancement

#341 GesCOF PDF improvements & partner + UGA experts ACL bugfix.
  components/com_emundus/controller.php
  components/com_emundus/controllers/files.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  libraries/emundus/pdf.php
  modules/mod_emundus_category_search/tmpl/fullWidth.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
  plugins/fabrik_form/php/scripts/emundus-UGA-expert_agreement.php
Labels: GesCOF, Module, Plugin, bugfix, enhancement, search engine

#345 Fixed incorrect displaying of number of days in list view.
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: bugfix, patch, search engine

#344 Fixed incorrect displaying of number of days in list view.
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Production, bugfix, patch, search engine

#346 🐛🛠 Fix days on details page + search field input
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: bugfix, filters, search engine

#347 CCIRS PDF improvements
  components/com_emundus/controllers/files.php
  libraries/emundus/pdf.php
Labels: Exports, enhancement

#348 CCIRS bugfixes on days + prefilter by person + PDF improvements
  components/com_emundus/controllers/files.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  libraries/emundus/pdf.php
Labels: Design, Exports, GesCOF, bugfix, enhancement, search engine

#349 CCIRS Phase 1 complete.
  components/com_emundus/controllers/files.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  libraries/emundus/pdf.php
Labels: Design, GesCOF, Production, bugfix, enhancement, search engine

#351 Date filter fix on clear filters
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: bugfix, patch, search engine

#352 Cccirs filter js patch
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Production, patch, search engine

#353 Fixed an error due to Fabrik filters having changing IDs
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: patch, search engine

#355 Small Friday improvements.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  plugins/fabrik_form/php/scripts/emundus-confirm_post.php
Labels: bugfix, enhancement

#358 CCIRS fixed Fabrik list bug, fixed popups, fixed insertion of duplicate sessions.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/fullWidth.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, bugfix, search engine

#359 Fixed some minor bugs present in CCIRS V1
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/fullWidth.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, bugfix, search engine

#360 Fixed some minor bugs present in CCIRS V1
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/fullWidth.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, Production, bugfix, search engine

#363 Minor SEO tweaks to CCIRS templates.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: search engine

#370 IMTA patch
  plugins/fabrik_form/emundusreferentletter/emundusreferentletter.php
  plugins/fabrik_form/emundusreferentletter/forms/fields.xml
Labels: Production, bugfix, patch

#374 Hesam improvements
  modules/mod_emundus_send_application/helper.php
  modules/mod_emundus_send_application/index.html
  modules/mod_emundus_send_application/language/en-GB/en-GB.mod_emundus_send_application.ini
  modules/mod_emundus_send_application/language/en-GB/en-GB.mod_emundus_send_application.sys.ini
  modules/mod_emundus_send_application/language/fr-FR/fr-FR.mod_emundus_send_application.ini
  modules/mod_emundus_send_application/language/fr-FR/fr-FR.mod_emundus_send_application.sys.ini
  modules/mod_emundus_send_application/mod_emundus_send_application.php
  modules/mod_emundus_send_application/mod_emundus_send_application.xml
  modules/mod_emundus_send_application/tmpl/default.php
  modules/mod_emundus_send_application/tmpl/index.html
  plugins/fabrik_form/emunduscampaign/emunduscampaign.php
Labels: Module, Plugin, bugfix, feature

#378 Added check on form completeness to the send form button.
  modules/mod_emundus_send_application/tmpl/default.php
  modules/mod_emundus_send_application/tmpl/hesam.php
Labels: bugfix

#379 Let's not talk about this...
  modules/mod_emundus_send_application/tmpl/default.php
  modules/mod_emundus_send_application/tmpl/hesam.php
Labels: bugfix, embarassing

#380 Attachement fix
  components/com_emundus/controllers/cifre.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
Labels: bugfix

#381 HESAM Attachement fix
  components/com_emundus/controllers/cifre.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
Labels: bugfix

#388 🎁 Added support for Cascadingdropdown checkboxes in repeat groups.
  components/com_emundus/models/application.php
  libraries/emundus/pdf.php
Labels: Fabrik, bugfix, feature

#392 Hesam patch
  components/com_emundus/models/stats.php
  modules/mod_emundus_applications/tmpl/hesam.php
  modules/mod_emundus_graphs/language/fr-FR/fr-FR.mod_emundus_graphs.ini
  modules/mod_emundus_graphs/tmpl/default.php
Labels: patch

#396 OUPS
  components/com_emundus/models/files.php
Labels: embarassing

#397 Dev
  components/com_emundus/models/files.php
Labels: embarassing

#406 files view name fix
  components/com_emundus/models/stats.php
Labels: bugfix

#405 Frontend fixes, improvements, and cleanup.
  components/com_emundus/helpers/files.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/stats.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_emundus/views/files/tmpl/default.php
  components/com_emundus/views/renew_application/tmpl/default.php
  media/com_emundus/css/emundus_files.css
  media/com_emundus/js/em_files.js
  templates/g5_helium/html/com_users/registration/default.php
Labels: Design, bugfix, enhancement

#409 Build 3.8.13/20181026
  components/com_emundus/helpers/files.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/stats.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_emundus/views/files/tmpl/default.php
  components/com_emundus/views/renew_application/tmpl/default.php
  media/com_emundus/css/emundus_files.css
  media/com_emundus/js/em_files.js
  templates/g5_helium/html/com_users/registration/default.php
Labels: Design, Production, bugfix, enhancement, filters

#411 Code style and optimizations
  components/com_emundus/helpers/files.php
  components/com_emundus/views/files/view.raw.php
  media/com_emundus/js/em_files.js
Labels: enhancement

#418 Fixed a bug causing file uploads to not redirect with the itemId when SEF was on.
  components/com_emundus/controller.php
  components/com_emundus/views/users/tmpl/default.php
Labels: bugfix

#420 Fixed uploaded files deletion causing SEF errors. Added fix for uploads not having an indicator of selected file on new template.
  components/com_emundus/controller.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/users/tmpl/default.php
  templates/g5_helium/html/com_users/registration/default.php
Labels: bugfix, embarassing

#425 Added new Fabrik plugin allowing automatic assignment of files to groups of the corresponding institution.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  plugins/fabrik_form/emundusassigntoinstitution/emundusassigntoinstitution.php
  plugins/fabrik_form/emundusassigntoinstitution/emundusassigntoinstitution.xml
  plugins/fabrik_form/emundusassigntoinstitution/forms/fields.xml
  plugins/fabrik_form/emundusassigntoinstitution/forms/index.html
  plugins/fabrik_form/emundusassigntoinstitution/index.html
  plugins/fabrik_form/emundusassigntoinstitution/language/en-GB/en-GB.plg_fabrik_form_emundusassigntoinstitution.ini
  plugins/fabrik_form/emundusassigntoinstitution/language/en-GB/en-GB.plg_fabrik_form_emundusassigntoinstitution.sys.ini
  plugins/fabrik_form/emundusassigntoinstitution/language/fr-FR/fr-FR.plg_fabrik_form_emundusassigntoinstitution.ini
  plugins/fabrik_form/emundusassigntoinstitution/language/fr-FR/fr-FR.plg_fabrik_form_emundusassigntoinstitution.sys.ini
Labels: Plugin, bugfix, feature

#423 Build 3.8.13/20181031
  administrator/components/com_falang/contentelements/emundus_setup_groups.xml
  components/com_emundus/controller.php
  components/com_emundus/models/files.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/users/tmpl/default.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  plugins/fabrik_form/emundusassigntoinstitution/emundusassigntoinstitution.php
  plugins/fabrik_form/emundusassigntoinstitution/emundusassigntoinstitution.xml
  plugins/fabrik_form/emundusassigntoinstitution/forms/fields.xml
  plugins/fabrik_form/emundusassigntoinstitution/forms/index.html
  plugins/fabrik_form/emundusassigntoinstitution/index.html
  plugins/fabrik_form/emundusassigntoinstitution/language/en-GB/en-GB.plg_fabrik_form_emundusassigntoinstitution.ini
  plugins/fabrik_form/emundusassigntoinstitution/language/en-GB/en-GB.plg_fabrik_form_emundusassigntoinstitution.sys.ini
  plugins/fabrik_form/emundusassigntoinstitution/language/fr-FR/fr-FR.plg_fabrik_form_emundusassigntoinstitution.ini
  plugins/fabrik_form/emundusassigntoinstitution/language/fr-FR/fr-FR.plg_fabrik_form_emundusassigntoinstitution.sys.ini
  templates/g5_helium/html/com_users/registration/default.php
Labels: Plugin, Production, bugfix, feature
