Repository emundus/v6, pull requests merged in 2018-11, with the labels that each got.

#428 Staging
  components/com_emundus/helpers/files.php
  components/com_emundus/models/application.php
  components/com_emundus/views/admission/tmpl/default.php
  components/com_emundus/views/application/tmpl/assoc_files.php
  components/com_emundus/views/application/tmpl/comment.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  plugins/fabrik_form/emundusassigntoinstitution/emundusassigntoinstitution.php
Labels: bugfix

#430 Fixed regstration template override JS ...
  templates/g5_helium/html/com_users/registration/default.php
Labels: bugfix, embarassing

#432 Registration jQuery fix
  templates/g5_helium/html/com_users/registration/default.php
Labels: bugfix

#438 Login registration redirect
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/campaign.php
  components/com_fabrik/views/form/tmpl/preselected-form102/custom_css_example.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default.zip
  components/com_fabrik/views/form/tmpl/preselected-form102/default_actions.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_buttons.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_details.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_above.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_none.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_side.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_relateddata.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup_row.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup_table.php
  components/com_fabrik/views/form/tmpl/preselected-form102/template_css.php
  modules/mod_dpcalendar_map/language/cs-CZ/cs-CZ.mod_dpcalendar_map.ini
  modules/mod_dpcalendar_map/language/cs-CZ/cs-CZ.mod_dpcalendar_map.sys.ini
  modules/mod_emundus_campaign/language/en-GB/en-GB.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/language/fr-FR/fr-FR.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundus_campaign/mod_emundus_campaign.xml
  modules/mod_emundus_campaign/tmpl/default_g5.php
  plugins/user/emundus/emundus.php
  templates/g5_helium/html/com_users/login/default.php
  templates/g5_helium/html/com_users/login/default.xml
  templates/g5_helium/html/com_users/login/default_login.php
  templates/g5_helium/html/com_users/login/default_logout.php
  templates/g5_helium/html/com_users/login/index.html
  templates/g5_helium/html/com_users/login/logout.xml
  templates/g5_helium/html/com_users/login/view.html.php
Labels: feature

#437 CCIRS PDF and other bugfixes.
  components/com_emundus/controllers/files.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/campaign.php
  components/com_fabrik/views/form/tmpl/preselected-form102/custom_css_example.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default.zip
  components/com_fabrik/views/form/tmpl/preselected-form102/default_actions.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_buttons.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_details.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_above.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_none.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_side.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_relateddata.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup_row.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup_table.php
  components/com_fabrik/views/form/tmpl/preselected-form102/template_css.php
  modules/mod_dpcalendar_map/language/cs-CZ/cs-CZ.mod_dpcalendar_map.ini
  modules/mod_dpcalendar_map/language/cs-CZ/cs-CZ.mod_dpcalendar_map.sys.ini
  modules/mod_emundus_campaign/language/en-GB/en-GB.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/language/fr-FR/fr-FR.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundus_campaign/mod_emundus_campaign.xml
  modules/mod_emundus_campaign/tmpl/default_g5.php
  modules/mod_emundus_category_search/tmpl/default.php
  plugins/user/emundus/emundus.php
  templates/g5_helium/html/com_users/login/default.php
  templates/g5_helium/html/com_users/login/default.xml
  templates/g5_helium/html/com_users/login/default_login.php
  templates/g5_helium/html/com_users/login/default_logout.php
  templates/g5_helium/html/com_users/login/index.html
  templates/g5_helium/html/com_users/login/logout.xml
  templates/g5_helium/html/com_users/login/view.html.php
  templates/g5_helium/html/com_users/registration/default.php
Labels: Exports, bugfix

#435 Build 3.8.13/20181109
  components/com_emundus/controllers/files.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/campaign.php
  components/com_fabrik/views/form/tmpl/preselected-form102/custom_css_example.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default.zip
  components/com_fabrik/views/form/tmpl/preselected-form102/default_actions.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_buttons.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_details.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_above.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_none.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_group_labels_side.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_relateddata.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup_row.php
  components/com_fabrik/views/form/tmpl/preselected-form102/default_repeatgroup_table.php
  components/com_fabrik/views/form/tmpl/preselected-form102/template_css.php
  modules/mod_dpcalendar_map/language/cs-CZ/cs-CZ.mod_dpcalendar_map.ini
  modules/mod_dpcalendar_map/language/cs-CZ/cs-CZ.mod_dpcalendar_map.sys.ini
  modules/mod_emundus_campaign/language/en-GB/en-GB.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/language/fr-FR/fr-FR.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundus_campaign/mod_emundus_campaign.xml
  modules/mod_emundus_campaign/tmpl/default_g5.php
  modules/mod_emundus_category_search/tmpl/default.php
  plugins/user/emundus/emundus.php
  templates/g5_helium/html/com_users/login/default.php
  templates/g5_helium/html/com_users/login/default.xml
  templates/g5_helium/html/com_users/login/default_login.php
  templates/g5_helium/html/com_users/login/default_logout.php
  templates/g5_helium/html/com_users/login/index.html
  templates/g5_helium/html/com_users/login/logout.xml
  templates/g5_helium/html/com_users/login/view.html.php
  templates/g5_helium/html/com_users/registration/default.php
Labels: Production, bugfix

#446 Admission query fix
  components/com_emundus/models/admission.php
Labels: Admission, bugfix

#445 Add buttons to consult the fabrik lists on dashboard
  modules/mod_emundus_campaign/tmpl/default_g5.php
  modules/mod_emundus_graphs/tmpl/default.php
Labels: Design, dashboard

#443 CCI Connect OAuth2 support
  components/com_emundus/controllers/users.php
  components/com_emundus/models/profile.php
  components/com_emundus/models/users.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.xml
  plugins/authentication/emundus_oauth2_cci/index.html
  plugins/authentication/emundus_oauth2_cci/language/en-GB/en-GB.plg_authentication_emundus_oauth2_cci.ini
  plugins/authentication/emundus_oauth2_cci/language/en-GB/en-GB.plg_authentication_emundus_oauth2_cci.sys.ini
  plugins/authentication/emundus_oauth2_cci/language/fr-FR/fr-FR.plg_authentication_emundus_oauth2_cci.ini
  plugins/authentication/emundus_oauth2_cci/language/fr-FR/fr-FR.plg_authentication_emundus_oauth2_cci.sys.ini
  plugins/system/oauth2/oauth2.php
  plugins/system/oauth2/oauth2.xml
  plugins/user/emundus/emundus.php
Labels: Plugin, feature, users

#449 Bugfix session code linked in the URL.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: bugfix, patch

#441 File attachment disable button on load and un-disable when file uplo…
  components/com_emundus/controllers/users.php
  components/com_emundus/emundus.php
  components/com_emundus/models/admission.php
  components/com_emundus/models/campaign.php
  components/com_emundus/models/decision.php
  components/com_emundus/models/profile.php
  components/com_emundus/models/users.php
  components/com_emundus/views/campaign/view.json.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/evaluation/tmpl/default.php
  components/com_emundus/views/export_select_columns/tmpl/default.php
  components/com_emundus/views/export_select_columns/view.raw.php
  components/com_emundus/views/profile/view.html.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_campaign/tmpl/default_g5.php
  modules/mod_emundus_graphs/tmpl/default.php
  modules/mod_emundusmenu/tmpl/gantry5.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.xml
  plugins/authentication/emundus_oauth2_cci/index.html
  plugins/authentication/emundus_oauth2_cci/language/en-GB/en-GB.plg_authentication_emundus_oauth2_cci.ini
  plugins/authentication/emundus_oauth2_cci/language/en-GB/en-GB.plg_authentication_emundus_oauth2_cci.sys.ini
  plugins/authentication/emundus_oauth2_cci/language/fr-FR/fr-FR.plg_authentication_emundus_oauth2_cci.ini
  plugins/authentication/emundus_oauth2_cci/language/fr-FR/fr-FR.plg_authentication_emundus_oauth2_cci.sys.ini
  plugins/system/oauth2/oauth2.php
  plugins/system/oauth2/oauth2.xml
  plugins/user/emundus/emundus.php
Labels: Plugin, bugfix, enhancement, feature

#451 Php office bugfix
  components/com_emundus/controllers/files.php
  libraries/vendor/composer/autoload_files.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: bugfix

#452 Fixed a bug with PHP Office and composer autoload, added support for HTML in the campaigns module.
  components/com_emundus/controllers/files.php
  libraries/vendor/composer/autoload_files.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  modules/mod_emundus_campaign/tmpl/default_g5.php
Labels: Design, bugfix, enhancement

#453 Updated autoload patch to include zend lib.
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: bugfix

#454 Updated autoload patch to include zend lib.
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: bugfix

#456 Fixed "Download in one document" feature.
  components/com_emundus/controllers/files.php
  libraries/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php
Labels: bugfix

#457 Fixed "Download in one document" feature.
  components/com_emundus/controllers/files.php
  libraries/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php
Labels: bugfix

#458 Fixed evaluation form being resized below the container.
  components/com_emundus/views/application/tmpl/evaluation.php
Labels: Evaluation, bugfix

#455 Build 6.8.13/20181126
  components/com_emundus/controllers/files.php
  components/com_emundus/views/application/tmpl/evaluation.php
  libraries/vendor/composer/autoload_files.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php
  modules/mod_emundus_campaign/tmpl/default_g5.php
Labels: Design, Production, bugfix, enhancement

#461 CCIRS improvements
  components/com_emundus/controllers/files.php
  components/com_emundus/models/files.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, Production, bugfix

#460 CCIRS improvements
  components/com_emundus/controllers/files.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, bugfix, enhancement

#462 fix sql error on files graph
  components/com_emundus/models/stats.php
  modules/mod_emundus_graphs/language/fr-FR/fr-FR.mod_emundus_graphs.ini
Labels: bugfix

#464 Build 3.8.13/20181129
  administrator/components/com_emundus/controllers/migration.php
  administrator/components/com_emundus/models/migration.php
  components/com_emundus/models/stats.php
  modules/mod_emundus_graphs/language/fr-FR/fr-FR.mod_emundus_graphs.ini
Labels: bugfix, embarassing, patch
