Repository emundus/v6, pull requests merged in 2018-09, with the labels that each got.

#228 Issue 227
  components/com_emundus/helpers/files.php
  components/com_emundus/models/emails.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_emundus/views/files/view.raw.php
  modules/mod_emundus_custom/index.html
  modules/mod_emundus_custom/language/en-GB/en-GB.mod_emundus_custom.ini
  modules/mod_emundus_custom/language/fr-FR/fr-FR.mod_emundus_custom.ini
  modules/mod_emundus_custom/mod_emundus_custom.php
  modules/mod_emundus_custom/mod_emundus_custom.xml
  modules/mod_emundus_custom/tmpl/default.php
  modules/mod_emundus_custom/tmpl/index.html
Labels: Component, enhancement, feature

#229 Custom HTML files view columns, improved dashboard graphs, bugfixes.
  components/com_emundus/helpers/files.php
  components/com_emundus/models/emails.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_emundus/views/files/view.raw.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/custom_css_example.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_actions.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_buttons.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_group.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_group_details.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_group_labels_above.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_group_labels_none.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_group_labels_side.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_relateddata.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_repeatgroup.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_repeatgroup_row.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default_repeatgroup_table.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/template_css.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/custom_css.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/custom_css_example.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_buttons.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_buttons_btn_group.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_headings.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_pagination.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_row.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_tabs.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default_togglecols.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/template_css.php
  modules/mod_emundus_custom/index.html
  modules/mod_emundus_custom/language/en-GB/en-GB.mod_emundus_custom.ini
  modules/mod_emundus_custom/language/fr-FR/fr-FR.mod_emundus_custom.ini
  modules/mod_emundus_custom/mod_emundus_custom.php
  modules/mod_emundus_custom/mod_emundus_custom.xml
  modules/mod_emundus_custom/tmpl/default.php
  modules/mod_emundus_custom/tmpl/index.html
  modules/mod_emundus_graphs/helper.php
  modules/mod_emundus_graphs/language/en-GB/en-GB.mod_emundus_graphs.ini
  modules/mod_emundus_graphs/language/fr-FR/fr-FR.mod_emundus_graphs.ini
  modules/mod_emundus_graphs/mod_emundus_graphs.php
  modules/mod_emundus_graphs/mod_emundus_graphs.xml
  modules/mod_emundus_graphs/tmpl/default.php
  plugins/fabrik_cron/migalFTP/forms/fields.xml
  plugins/fabrik_cron/migal_ftp/files/.gitignore
  plugins/fabrik_cron/migal_ftp/files/index.html
  plugins/fabrik_cron/migal_ftp/forms/fields.xml
  plugins/fabrik_cron/migal_ftp/forms/index.html
  plugins/fabrik_cron/migal_ftp/index.html
  plugins/fabrik_cron/migal_ftp/language/en-GB/en-GB.plg_fabrik_cron_migalFTP.ini
  plugins/fabrik_cron/migal_ftp/language/en-GB/en-GB.plg_fabrik_cron_migalFTP.sys.ini
  plugins/fabrik_cron/migal_ftp/language/fr-FR/fr-FR.plg_fabrik_cron_migalFTP.ini
  plugins/fabrik_cron/migal_ftp/language/fr-FR/fr-FR.plg_fabrik_cron_migalFTP.sys.ini
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.xml
Labels: Module, bugfix, enhancement, feature

#230 CCI list view improvements.
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Fabrik, enhancement, feature

#234 Improvements to CCIRS Search template.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, bugfix, enhancement, search engine

#241 Added more fields to the MigalFTP script.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, patch

#242 Gescof updates
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, patch

#245 🐛🛠 GMaps no localization fix
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: bugfix, patch

#246 🐛🛠 GMaps no localization fix
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: Production, bugfix, patch

#248 🐛🛠 Fixed a few bugs linked to the Migal plugin.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: bugfix, patch

#250 🐛🛠 Fixed a bug linked to the Migal plugin.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: bugfix, patch

#251 🐛🛠 Fixed a bug linked to the Migal plugin.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: Production, bugfix, patch

#252 🐛🛠 Details localization Fix
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: bugfix, patch

#253 🐛🛠 Details localization Fix
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: Production, bugfix, patch

#254 🐛🛠 Fixed the template CSS missing closing HTML tags.
  administrator/components/com_admin/sql/updates/mysql/3.8.12-2018-09-18-em.sql
Labels: bugfix, emails

#255 🎁 GesCOF improvements
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, enhancement

#256 🐛🛠 Added category order.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, bugfix

#257 🎁 Category search module for CCIRS.
  modules/mod_emundus_category_search/helper.php
  modules/mod_emundus_category_search/index.html
  modules/mod_emundus_category_search/language/en-GB/en-GB.mod_emundus_category_search.ini
  modules/mod_emundus_category_search/language/fr-FR/fr-FR.mod_emundus_category_search.ini
  modules/mod_emundus_category_search/mod_emundus_category_search.php
  modules/mod_emundus_category_search/mod_emundus_category_search.xml
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/index.html
Labels: Module, feature

#258 🎨 Changed modal templates to assist integration.
  modules/mod_emundus_cifre_offers/tmpl/default.php
  modules/mod_emundus_cifre_suggestions/tmpl/default.php
Labels: Module

#262 💾 Changes GesCOF script to implement a new structure. Information abo…
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF

#266 🖥♻&🐛🛠 Fixed the CCIRS search engine front-end.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Design, bugfix, search engine

#267 Major search engine frontend updates and GesCOF importation data structure changes.
  administrator/components/com_admin/sql/updates/mysql/3.8.12-2018-09-18-em.sql
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/files.php
  components/com_emundus/models/stats.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  modules/mod_emundus_category_search/helper.php
  modules/mod_emundus_category_search/index.html
  modules/mod_emundus_category_search/language/en-GB/en-GB.mod_emundus_category_search.ini
  modules/mod_emundus_category_search/language/fr-FR/fr-FR.mod_emundus_category_search.ini
  modules/mod_emundus_category_search/mod_emundus_category_search.php
  modules/mod_emundus_category_search/mod_emundus_category_search.xml
  modules/mod_emundus_category_search/tmpl/default.php
  modules/mod_emundus_category_search/tmpl/index.html
  modules/mod_emundus_cifre_offers/tmpl/default.php
  modules/mod_emundus_cifre_suggestions/tmpl/default.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: Design, GesCOF, Production, bugfix, search engine

#269 🐛🛠Fixed GesCOF category insertion queries for MariaDB compatibility.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, bugfix, patch

#270 🐛🛠 Fixed category links when backoffice value contained spaces and accents.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  modules/mod_emundus_category_search/tmpl/default.php
Labels: GesCOF, bugfix, search engine

#271 🐛🛠 Fixed category links when backoffice value contained spaces and accents and removed training PHP tags.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  modules/mod_emundus_category_search/tmpl/default.php
Labels: GesCOF, bugfix, patch, search engine

#273 Cci details css
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: Design, GesCOF, patch

#275 Fixed minor errors.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: patch

#277 Search engine rebuild
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Design, Fabrik, GesCOF, Production

#278 added html entity decode for GESCOF data
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Labels: Design, Fabrik, search engine

#281 Added manager firstname and lastname fields as well as product tax rate.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, patch

#282 Added manager firstname and lastname fields as well as product tax rate.
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: GesCOF, Production, patch

#284 🐛🛠 Fixed replacement regex and TCPDF issues linked to empty HTML tags.
  components/com_emundus/controllers/files.php
Labels: Exports, GesCOF, bugfix

#287 🐛🛠 remaining places alert
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Labels: GesCOF

#290 Ccirs formation details + list
  components/com_emundus/models/files.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  modules/mod_emundus_category_search/tmpl/default.php
Labels: bugfix, patch, search engine
