Repository emundus/v6, pull requests merged in 2019-07, with the labels that each got.

#712 Updated class names for the filters and other minor bugfixes.
  components/com_emundus/controllers/trombinoscope.php
  components/com_emundus/helpers/emails.php
  components/com_emundus/helpers/files.php
  components/com_emundus/models/application.php
  components/com_emundus/views/admission/tmpl/data.php
  components/com_emundus/views/admission/tmpl/default.php
  components/com_emundus/views/application/tmpl/admission.php
  components/com_emundus/views/application/tmpl/assoc_files.php
  components/com_emundus/views/application/tmpl/attachment.php
  components/com_emundus/views/application/tmpl/comment.php
  components/com_emundus/views/application/tmpl/decision.php
  components/com_emundus/views/application/tmpl/evaluation.php
  components/com_emundus/views/application/tmpl/form.php
  components/com_emundus/views/application/tmpl/mail.php
  components/com_emundus/views/application/tmpl/share.php
  components/com_emundus/views/application/tmpl/tag.php
  components/com_emundus/views/campaign/tmpl/default.php
  components/com_emundus/views/checklist/tmpl/attachments.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/checklist/tmpl/paid.php
  components/com_emundus/views/controlfiles/tmpl/default.php
  components/com_emundus/views/decision/tmpl/data.php
  components/com_emundus/views/decision/tmpl/default.php
  components/com_emundus/views/email/tmpl/default.php
  components/com_emundus/views/evaluation/tmpl/data.php
  components/com_emundus/views/evaluation/tmpl/default.php
  components/com_emundus/views/files/tmpl/access.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_emundus/views/files/tmpl/default.php
  components/com_emundus/views/files/tmpl/menuactions.php
  components/com_emundus/views/filesbystatus/tmpl/access.php
  components/com_emundus/views/filesbystatus/tmpl/data.php
  components/com_emundus/views/filesbystatus/tmpl/default.php
  components/com_emundus/views/filesbystatus/tmpl/menuactions.php
  components/com_emundus/views/jobs/tmpl/default_filter.php
  components/com_emundus/views/message/tmpl/default.php
  components/com_emundus/views/messages/tmpl/chat.php
  components/com_emundus/views/messages/tmpl/default.php
  components/com_emundus/views/profile/tmpl/default.php
  components/com_emundus/views/programme/tmpl/default.php
  components/com_emundus/views/trombinoscope/tmpl/default.php
  components/com_emundus/views/users/tmpl/addgroup.php
  components/com_emundus/views/users/tmpl/adduser.php
  components/com_emundus/views/users/tmpl/affectgroup.php
  components/com_emundus/views/users/tmpl/default.php
  components/com_emundus/views/users/tmpl/showgrouprights.php
  components/com_emundus/views/users/tmpl/showrights.php
  components/com_emundus/views/users/tmpl/user.php
  libraries/emundus/pdf_emploi.php
  libraries/emundus/pdf_evaluationpiu.php
  media/com_emundus/css/emundus_files.css
  modules/mod_emundus_campaign/tmpl/default_g5.php
  plugins/fabrik_list/su_copy_fiche_emplois/su_copy_fiche_emplois.php
  templates/g5_heliumOld2/fields/warning.php
Labels: Design, bugfix, enhancement

#713 Fixed two major bugs in the users view.
  components/com_emundus/views/users/tmpl/user.php
Labels: bugfix

#714 Fixed two major bugs in the users view.
  components/com_emundus/views/users/tmpl/user.php
Labels: bugfix

#715 Fixed a broken query in the updatePDF plugin.
  plugins/fabrik_form/emundusupdatepdf/emundusupdatepdf.php
Labels: bugfix

#717 Reverted an accidental deletion of the status display.
  modules/mod_emundus_applications/language/en-GB/en-GB.mod_emundus_applications.ini
  modules/mod_emundus_applications/language/fr-FR/fr-FR.mod_emundus_applications.ini
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_applications/mod_emundus_applications.xml
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  modules/mod_emundus_applications/tmpl/hesam.php
  modules/mod_emundus_applications/tmpl/nanomed.php
  modules/mod_emundus_applications/tmpl/ti.php
Labels: bugfix, embarassing

#720 General improvements and bugfixes.
  components/com_emundus/models/emails.php
  components/com_emundus/models/users.php
  components/com_emundus/views/application/tmpl/attachment.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_fabrik/views/list/tmpl/cci_documents/default.php
  modules/mod_emundus_applications/language/en-GB/en-GB.mod_emundus_applications.ini
  modules/mod_emundus_applications/language/fr-FR/fr-FR.mod_emundus_applications.ini
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_applications/mod_emundus_applications.xml
  modules/mod_emundus_applications/tmpl/esiea.php
Labels: Quality of life, bugfix, enhancement

#722 Tiny bugfixes to make everything just a little bit better.
  components/com_emundus/views/message/tmpl/default.php
  modules/mod_emundus_user_dropdown/mod_emundus_user_dropdown.php
  plugins/fabrik_form/emundusupdatepdf/emundusupdatepdf.php
Labels: bugfix

#716 Reorganise and dispatch css of custom-css.css
  .idea/workspace.xml
  components/com_emundus/controllers/messages.php
  components/com_emundus/emundus.php
  components/com_emundus/views/checklist/tmpl/application_form.php
  components/com_emundus/views/checklist/tmpl/application_form_pepite.php
  components/com_emundus/views/checklist/tmpl/attach_needed.php
  components/com_emundus/views/checklist/tmpl/attachments.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/checklist/tmpl/opt_attach.php
  components/com_emundus/views/export_select_columns/tmpl/default.php
  components/com_emundus/views/export_select_columns/tmpl/programme.php
  components/com_emundus/views/message/tmpl/default.php
  components/com_fabrik/views/form/tmpl/bootstrap/custom_css.php
  components/com_fabrik/views/form/tmpl/bootstrap/custom_css.zip
  components/com_fabrik/views/form/tmpl/bootstrap/default.zip
  components/com_fabrik/views/list/tmpl/bootstrap/custom_css.php
  components/com_fabrik/views/list/tmpl/bootstrap/custom_css.zip
  media/com_emundus/css/emundus.css
  media/com_emundus/css/emundus_checklist.css
  media/com_emundus/css/emundus_export_select_columns.css
  media/com_emundus/css/emundus_files.css
  media/com_emundus/css/emundus_trombinoscope.css
  media/com_emundus/css/reset.css
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_applications/style/mod_emundus_applications.css
  modules/mod_emundus_campaign/css/mod_emundus_campaign.css
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundus_checklist/mod_emundus_checklist.php
  modules/mod_emundus_checklist/mod_emundus_checklist.xml
  modules/mod_emundus_graphs/mod_emundus_graphs.php
  modules/mod_emundus_graphs/style/mod_emundus_graph.css
  modules/mod_emundus_user_dropdown/style/mod_emundus_user_dropdown.css
  modules/mod_emundus_user_dropdown/tmpl/default.php
  modules/mod_emundusflow/mod_emundusflow.php
  modules/mod_emundusflow/style/emundus.css
  modules/mod_emundusmenu/mod_emundusmenu.php
  modules/mod_emundusmenu/style/mod_emundusmenu.css
  modules/mod_emunduspanel/mod_emunduspanel.php
  modules/mod_emunduspanel/mod_emunduspanel.xml
  modules/mod_emunduspanel/style/emundus.css
  modules/mod_emunduspanel/tmpl/default.php
  plugins/system/J2top/J2top.php
  plugins/system/J2top/style/J2top.css
  templates/g5_helium/blueprints/styles/base.yaml
  templates/g5_helium/custom/.gitignore
  templates/g5_helium/html/com_users/login/default_login.php
  templates/g5_helium/html/com_users/login/style/com_users_login.css
Labels: Design

#724 Another wave of bugfixes
  components/com_emundus/controllers/messages.php
  components/com_emundus/emundus.php
  components/com_emundus/helpers/files.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/files.php
  components/com_emundus/views/application/tmpl/mail.php
  components/com_emundus/views/message/tmpl/default.php
  components/com_fabrik/views/list/tmpl/cci_documents/default.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/custom_css.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/custom_css_example.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/default.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/default_buttons.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/default_buttons_btn_group.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/default_headings.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/default_pagination.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/default_row.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/default_tabs.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/default_togglecols.php
  components/com_fabrik/views/list/tmpl/cci_stagiaire_documents/template_css.php
  libraries/emundus/pdf_evaluation.php
  media/com_emundus/css/emundus_trombinoscope.css
  media/com_emundus/js/em_files.js
  modules/mod_emundus_campaign/tmpl/default_g5.php
  plugins/fabrik_form/emundusconfirmrgpd/forms/fields.xml
  plugins/fabrik_form/emundusconfirmrgpd/language/en-GB/en-GB.plg_fabrik_form_emundusconfirmrgpd.ini
  plugins/fabrik_form/emundusconfirmrgpd/language/fr-FR/fr-FR.plg_fabrik_form_emundusconfirmrgpd.ini
  plugins/fabrik_form/emundusrequestrgpd/emundusrequestrgpd.php
  plugins/fabrik_form/emundusrequestrgpd/forms/fields.xml
  plugins/fabrik_form/emundusrequestrgpd/language/en-GB/en-GB.plg_fabrik_form_emundusrequestrgpd.ini
  plugins/fabrik_form/emundusrequestrgpd/language/fr-FR/fr-FR.plg_fabrik_form_emundusrequestrgpd.ini
  plugins/fabrik_form/emundusrgpd/emundusrgpd.php
  plugins/fabrik_form/emundusrgpd/forms/fields.xml
Labels: bugfix

#730 Reorganise css
  components/com_fabrik/views/form/tmpl/bootstrap/custom_css.php
  components/com_fabrik/views/form/tmpl/bootstrap/custom_css.zip
  components/com_fabrik/views/list/tmpl/bootstrap/custom_css.php
  components/com_fabrik/views/list/tmpl/bootstrap/custom_css.zip
  media/com_emundus/css/emundus.css
  media/com_emundus/css/emundus_checklist.css
  media/com_emundus/css/emundus_files.css
  modules/mod_emundus_applications/style/mod_emundus_applications.css
  modules/mod_emundus_campaign/css/mod_emundus_campaign.css
  modules/mod_emundus_graphs/style/mod_emundus_graph.css
  modules/mod_emundus_user_dropdown/style/mod_emundus_user_dropdown.css
  modules/mod_emundusflow/style/emundus.css
  modules/mod_emundusmenu/style/mod_emundusmenu.css
  modules/mod_emunduspanel/style/emundus.css
  plugins/system/J2top/style/J2top.css
  templates/g5_helium/custom/.gitignore
  templates/g5_helium/custom/blueprints/styles/base.yaml
  templates/g5_helium/custom/scss/custom.scss
  templates/g5_helium/html/com_users/login/default_logout.php
  templates/g5_helium/html/com_users/login/style/com_users_login.css
  templates/g5_helium/html/com_users/profile/edit.php
  templates/g5_helium/html/com_users/profile/style/com_users_profile.css
Labels: bugfix

#731 Built eMundus Claroline plugin
  plugins/user/emundus_claroline/emundus_claroline.php
  plugins/user/emundus_claroline/emundus_claroline.xml
  plugins/user/emundus_claroline/index.html
Labels: Plugin, feature, users

#734 eMundus plugin system, added plugins for institut francais, also fixed a lot of little bugs.
  administrator/components/com_admin/sql/updates/mysql/3.9.10-2019-07-19-em.sql
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/controller.php
  components/com_emundus/controllers/files.php
  components/com_emundus/controllers/messages.php
  components/com_emundus/helpers/export.php
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/files.php
  components/com_emundus/models/messages.php
  components/com_emundus/models/users.php
  components/com_emundus/views/application/tmpl/attachment.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/job/tmpl/default.php
  components/com_emundus/views/message/tmpl/default.php
  components/com_emundus/views/profile/tmpl/default.php
  modules/mod_emundus_campaign/helper.php
  modules/mod_emundus_campaign/language/en-GB/en-GB.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/language/fr-FR/fr-FR.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundus_campaign/mod_emundus_campaign.xml
  modules/mod_emundus_campaign/tmpl/institut_fr.php
  plugins/emundus/send_file_archive/index.html
  plugins/emundus/send_file_archive/send_file_archive.php
  plugins/emundus/send_file_archive/send_file_archive.xml
  plugins/fabrik_form/php/scripts/emundus-ccirs-campaign-multi.php
  plugins/user/emundus/emundus.php
  plugins/user/emundus_claroline/emundus_claroline.php
  plugins/user/emundus_claroline/emundus_claroline.xml
  plugins/user/emundus_claroline/index.html
  plugins/user/emundus_user_recap/emundus_user_recap.php
  plugins/user/emundus_user_recap/emundus_user_recap.xml
  plugins/user/emundus_user_recap/index.html
Labels: Plugin, bugfix, feature

#735 Updated the user_recap plugin to include a text tag for the number of files deleted.
  plugins/user/emundus_user_recap/emundus_user_recap.php
  plugins/user/emundus_user_recap/emundus_user_recap.xml
  plugins/user/emundus_user_recap/language/en-GB/en-GB.plg_user_emundus_user_recap.ini
  plugins/user/emundus_user_recap/language/fr-FR/fr-FR.plg_user_emundus_user_recap.ini
  plugins/user/emundus_user_recap/language/index.html
Labels: Plugin

#728 Features to add color to assoc tag
  components/com_emundus/models/files.php
Labels: Design, enhancement

#736 Added colors to group tags in the files view.
  administrator/components/com_admin/sql/updates/mysql/3.9.10-2019-07-24-em.sql
  components/com_emundus/models/files.php
  modules/mod_emundus_campaign/tmpl/institut_fr.php
Labels: Design, feature

#738 Added ability to color the users the files are associated to and added year element.
  administrator/components/com_admin/sql/updates/mysql/3.9.10-2019-07-24-em.sql
  components/com_emundus/models/files.php
  plugins/fabrik_element/years/forms/fields.xml
  plugins/fabrik_element/years/forms/index.html
  plugins/fabrik_element/years/index.html
  plugins/fabrik_element/years/language/da-DK/da-DK.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/da-DK/da-DK.plg_fabrik_element_birthday.sys.ini
  plugins/fabrik_element/years/language/da-DK/index.html
  plugins/fabrik_element/years/language/de-DE/de-DE.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/de-DE/de-DE.plg_fabrik_element_birthday.sys.ini
  plugins/fabrik_element/years/language/de-DE/index.html
  plugins/fabrik_element/years/language/en-GB/en-GB.plg_fabrik_element_birthday_remove_slashes.ini
  plugins/fabrik_element/years/language/en-GB/en-GB.plg_fabrik_element_birthday_remove_slashes.sys.ini
  plugins/fabrik_element/years/language/en-GB/index.html
  plugins/fabrik_element/years/language/es-ES/es-ES.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/es-ES/es-ES.plg_fabrik_element_birthday.sys.ini
  plugins/fabrik_element/years/language/es-ES/index.html
  plugins/fabrik_element/years/language/et-EE/et-EE.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/et-EE/et-EE.plg_fabrik_element_birthday.sys.ini
  plugins/fabrik_element/years/language/et-EE/index.html
  plugins/fabrik_element/years/language/eu-ES/eu-ES.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/fr-FR/fr-FR.plg_fabrik_element_birthday_remove_slashes.ini
  plugins/fabrik_element/years/language/fr-FR/fr-FR.plg_fabrik_element_birthday_remove_slashes.sys.ini
  plugins/fabrik_element/years/language/fr-FR/index.html
  plugins/fabrik_element/years/language/index.html
  plugins/fabrik_element/years/language/it-IT/index.html
  plugins/fabrik_element/years/language/it-IT/it-IT.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/it-IT/it-IT.plg_fabrik_element_birthday.sys.ini
  plugins/fabrik_element/years/language/ms-MY/ms-MY.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/nl-NL/index.html
  plugins/fabrik_element/years/language/nl-NL/nl-NL.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/pl-PL/pl-PL.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/pt-BR/index.html
  plugins/fabrik_element/years/language/pt-BR/pt-BR.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/pt-PT/pt-PT.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/pt-PT/pt-PT.plg_fabrik_element_birthday.sys.ini
  plugins/fabrik_element/years/language/ro-RO/index.html
  plugins/fabrik_element/years/language/ro-RO/ro-RO.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/ru-RU/index.html
  plugins/fabrik_element/years/language/ru-RU/ru-RU.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/language/ru-RU/ru-RU.plg_fabrik_element_birthday.sys.ini
  plugins/fabrik_element/years/language/sk-SK/sk-SK.plg_fabrik_element_birthday.ini
  plugins/fabrik_element/years/layouts/fabrik-element-birthday-filter-select-day-month-year.php
  plugins/fabrik_element/years/layouts/fabrik-element-years-detail.php
  plugins/fabrik_element/years/layouts/fabrik-element-years-form.php
  plugins/fabrik_element/years/years-min.js
  plugins/fabrik_element/years/years.js
  plugins/fabrik_element/years/years.php
  plugins/fabrik_element/years/years.xml
Labels: Design, enhancement
