Repository emundus/v6, pull requests merged in 2019-12, with the labels that each got.

#848 Bugfixes in letter generation and decision list view.
  administrator/components/com_admin/sql/updates/mysql/3.9.12-2019-11-26-em.sql
  administrator/components/com_falang/contentelements/emundus_setup_attachments.xml
  administrator/components/com_falang/contentelements/emundus_setup_campaigns.xml
  administrator/components/com_falang/contentelements/emundus_setup_checklist.xml
  administrator/components/com_falang/contentelements/emundus_setup_emails.xml
  administrator/components/com_falang/contentelements/emundus_setup_groups.xml
  administrator/components/com_falang/contentelements/emundus_setup_mobility.xml
  administrator/components/com_falang/contentelements/emundus_setup_profiles.xml
  administrator/components/com_falang/contentelements/emundus_setup_programmes.xml
  administrator/components/com_falang/contentelements/emundus_setup_status.xml
  components/com_emundus/controllers/files.php
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/decision.php
Labels: bugfix, translation

#849 emundus hikashop plugin modifications
  administrator/components/com_admin/sql/updates/mysql/3.9.12-2019-11-26-em.sql
  components/com_emundus/views/export_select_columns/tmpl/all_programs.php
  modules/mod_emundus_applications/tmpl/esiea.php
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundusflow/tmpl/esiea.php
  plugins/hikashop/emundus_hikashop/emundus_hikashop.php
Labels: Plugin, payment

#846 Build 6.9.13/20191127
  administrator/components/com_admin/sql/updates/mysql/3.9.12-2019-11-26-em.sql
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  administrator/components/com_falang/contentelements/emundus_setup_attachments.xml
  administrator/components/com_falang/contentelements/emundus_setup_campaigns.xml
  administrator/components/com_falang/contentelements/emundus_setup_checklist.xml
  administrator/components/com_falang/contentelements/emundus_setup_emails.xml
  administrator/components/com_falang/contentelements/emundus_setup_groups.xml
  administrator/components/com_falang/contentelements/emundus_setup_mobility.xml
  administrator/components/com_falang/contentelements/emundus_setup_profiles.xml
  administrator/components/com_falang/contentelements/emundus_setup_programmes.xml
  administrator/components/com_falang/contentelements/emundus_setup_status.xml
  components/com_emundus/controllers/admission.php
  components/com_emundus/controllers/decision.php
  components/com_emundus/controllers/evaluation.php
  components/com_emundus/controllers/files.php
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  components/com_emundus/models/decision.php
  components/com_emundus/models/files.php
  components/com_emundus/views/application/view.html.php
  components/com_emundus/views/application/view.raw.php
  components/com_emundus/views/checklist/view.html.php
  components/com_emundus/views/export_select_columns/tmpl/all_programs.php
  components/com_fabrik/views/form/tmpl/bootstrap/default.php
  components/com_fabrik/views/form/tmpl/bootstrap/default.zip
  libraries/emundus/pdf_evaluationrin100.php
  libraries/emundus/pdf_evaluationrin50.php
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_applications/tmpl/esiea.php
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundus_send_application/mod_emundus_send_application.php
  modules/mod_emundusflow/mod_emundusflow.php
  modules/mod_emundusflow/tmpl/default.php
  modules/mod_emundusflow/tmpl/esiea.php
  plugins/emundus/aurion_sync_setup_campaigns_excelia/aurion_sync_setup_campaigns_excelia.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
  plugins/fabrik_form/emunduscompletefilestatuschange/emunduscompletefilestatuschange.php
  plugins/fabrik_form/php/scripts/emundus-PEPITE-isApplicationCompleted.php
  plugins/fabrik_form/php/scripts/emundus-isApplicationCompleted.php
  plugins/hikashop/emundus_hikashop/emundus_hikashop.php
  plugins/hikashop/emundus_hikashop/emundus_hikashop.xml
  plugins/hikashop/emundus_hikashop/language/en-GB/en-GB.plg_hikashop_emundus_hikashop.ini
  plugins/hikashop/emundus_hikashop/language/en-GB/en-GBplg_hikashop_emundus_hikashop.sys.ini
  plugins/hikashop/emundus_hikashop/language/fr-FR/fr-FR.plg_hikashop_emundus_hikashop.ini
  plugins/hikashop/emundus_hikashop/language/fr-FR/fr-FR.plg_hikashop_emundus_hikashop.sys.ini
Labels: GesCOF, Production, bugfix, payment, translation

#853 application menu
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  media/com_emundus/js/em_files.js
Labels: embarassing

#854 Recovery 6.9.13/20191212
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  media/com_emundus/js/em_files.js
Labels: Production, bugfix

#857 Build 6.9.13/20191216
  components/com_fabrik/views/list/tmpl/cci_companys/default.php
Labels: Fabrik
