Repository emundus/v6, pull requests merged in 2019-02, with the labels that each got.

#544 Removed check on limit date.
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
Labels: search engine

#545 Added additional security to file uploads and added more info to the search engine.
  components/com_emundus/controllers/messages.php
  components/com_emundus/helpers/list.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
Labels: bugfix, search engine

#541 Build 3.9.2/20190131
  components/com_emundus/controllers/cifre.php
  components/com_emundus/controllers/messages.php
  components/com_emundus/helpers/list.php
  components/com_emundus/models/admission.php
  components/com_emundus/models/campaign.php
  components/com_emundus/models/cifre.php
  components/com_emundus/models/decision.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/views/campaign/view.json.php
  components/com_emundus/views/export_select_columns/tmpl/default.php
  components/com_emundus/views/export_select_columns/view.raw.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
  media/com_emundus/js/em_files.js
  modules/mod_emundus_applications/helper.php
  modules/mod_emundus_applications/tmpl/hesam.php
  modules/mod_emundus_cifre_offers/language/en-GB/en-GB.mod_emundus_cifre_offers.ini
  modules/mod_emundus_cifre_offers/language/fr-FR/fr-FR.mod_emundus_cifre_offers.ini
  modules/mod_emundus_cifre_offers/tmpl/default.php
  modules/mod_emundus_message_notification/tmpl/dropdown_menu.php
  plugins/fabrik_form/emundusisapplicationsent/emundusisapplicationsent.php
  plugins/fabrik_form/emunduspushfiletoapi/emunduspushfiletoapi.php
  plugins/fabrik_form/emunduspushfiletoapi/emunduspushfiletoapi.xml
  plugins/fabrik_form/emunduspushfiletoapi/forms/fields.xml
  plugins/fabrik_form/emunduspushfiletoapi/forms/index.html
  plugins/fabrik_form/emunduspushfiletoapi/index.html
  plugins/fabrik_form/emunduspushfiletoapi/language/en-GB/en-GB.plg_fabrik_form_emunduspushfiletoapi.ini
  plugins/fabrik_form/emunduspushfiletoapi/language/en-GB/en-GB.plg_fabrik_form_emunduspushfiletoapi.sys.ini
  plugins/fabrik_form/emunduspushfiletoapi/language/fr-FR/fr-FR.plg_fabrik_form_emunduspushfiletoapi.ini
  plugins/fabrik_form/emunduspushfiletoapi/language/fr-FR/fr-FR.plg_fabrik_form_emunduspushfiletoapi.sys.ini
  plugins/fabrik_form/php/scripts/emundus-ESIEA-admission-redirect.php
  plugins/fabrik_form/php/scripts/emundus-HESAM-INSCRIPTION-all-regions-departments.php
  plugins/fabrik_form/php/scripts/emundus-HESAM-all-regions-departments.php
Labels: Production, bugfix, enhancement, search engine

#550 Added ability to link a profile to a status
  administrator/components/com_admin/sql/updates/mysql/3.9.1-2019-02-05-em.sql
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/files.php
  components/com_emundus/views/admission/tmpl/data.php
  components/com_emundus/views/decision/tmpl/data.php
  components/com_emundus/views/evaluation/tmpl/data.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_emundus/views/filesbystatus/tmpl/data.php
  media/com_emundus/css/emundus_files.css
Labels: bugfix, feature

#551 Added the status/profile linkage to the admission pipeline.
  components/com_emundus/controllers/files.php
  components/com_emundus/models/admission.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/files.php
  modules/mod_emundus_cifre_offers/language/fr-FR/fr-FR.mod_emundus_cifre_offers.ini
Labels: bugfix, feature

#552 Added programmatic recuperation of itemId in admission info code used…
  components/com_emundus/models/admission.php
  components/com_emundus/models/profile.php
Labels: feature

#553 Fixed an issue causing users to be redirected to their admission form…
  components/com_emundus/models/profile.php
Labels: bugfix

#554 Fixed query in admission itemId.
  components/com_emundus/models/admission.php
Labels: bugfix

#556 Added automatic user activation on CSV import.
  modules/mod_emundus_applications/tmpl/esiea.php
  plugins/fabrik_form/php/scripts/emundus-csv_import.php
Labels: bugfix, enhancement

#557 Fixed a bug in the multi-profile system and the admission redirect.
  components/com_emundus/models/cifre.php
  components/com_emundus/models/profile.php
  components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  modules/mod_emundus_cifre_offers/tmpl/default.php
  plugins/fabrik_form/php/scripts/emundus-ESIEA-admission-redirect.php
Labels: Admission, bugfix

#559 Added ability to toggle whether or not fees with scholarship have to be paid or not.
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
  plugins/fabrik_form/php/scripts/emundus-isApplicationCompleted.php
Labels: bugfix, feature

#561 Fixed an edge case where we could be redirected to the admission form…
  components/com_emundus/models/profile.php
Labels: Admission, bugfix

#562 Payment system improvements.
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  components/com_emundus/views/checklist/view.html.php
  modules/mod_emundus_applications/tmpl/esiea.php
Labels: enhancement, feature, payment

#564 HESAM modifications + Fixed evaluation query edge case.
  components/com_emundus/models/cifre.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/users.php
  components/com_emundus/views/messages/tmpl/default.php
  components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
  modules/mod_emundus_applications/language/fr-FR/fr-FR.mod_emundus_applications.ini
  modules/mod_emundus_applications/tmpl/hesam.php
  modules/mod_emundus_cifre_offers/tmpl/default.php
  modules/mod_emundus_message_notification/tmpl/dropdown_menu.php
Labels: Design, bugfix

#565 Fixed HESAM bugs.
  components/com_emundus/models/cifre.php
  components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
Labels: bugfix, embarassing

#567 Black magic 2: Electric boogaloo
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: Exports, Production, patch

#574 Document generation improvements.
  components/com_emundus/controllers/files.php
  components/com_emundus/helpers/files.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/files.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: Exports, bugfix

#575 Fixed some bugs linked to document generation.
  components/com_emundus/controllers/files.php
  components/com_emundus/helpers/files.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/files.php
  components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: bugfix

#584 Hesam message system improvements.
  components/com_emundus/controllers/cifre.php
  components/com_emundus/controllers/messages.php
  components/com_emundus/models/cifre.php
  components/com_emundus/models/messages.php
  components/com_emundus/views/messages/tmpl/chat.php
  components/com_emundus/views/messages/tmpl/default.php
  components/com_emundus/views/messages/view.html.php
  components/com_emundus/views/messages/view.raw.php
  modules/mod_emundus_cifre_offers/tmpl/default.php
Labels: feature

#589 Fixed some of the recent modifications to CCIRS.
  components/com_emundus/controllers/files.php
  components/com_emundus/views/campaign/view.json.php
Labels: bugfix

#588 Fixed some of the recent modifications to CCIRS.
  components/com_emundus/controllers/files.php
  components/com_emundus/views/campaign/view.json.php
  modules/mod_emunduspanel/mod_emunduspanel.php
  modules/mod_emunduspanel/tmpl/default.php
Labels: Production, bugfix, patch

#591 Fixed some additional bugs in the CCIRS modifications.
  components/com_emundus/controllers/files.php
Labels: bugfix

#590 Fixed some additional bugs in the CCIRS modifications.
  components/com_emundus/controllers/files.php
Labels: Production, bugfix, patch

#592 Improved HESAM chat, fixed some things for CCIRS and fixed IMT plugin.
  components/com_emundus/controllers/cifre.php
  components/com_emundus/controllers/files.php
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/views/campaign/view.json.php
  components/com_emundus/views/messages/tmpl/chat.php
  modules/mod_emunduspanel/mod_emunduspanel.php
  modules/mod_emunduspanel/tmpl/default.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.php
  plugins/authentication/emundus_oauth2_cci/language/en-GB/en-GB.plg_authentication_emundus_oauth2_cci.ini
  plugins/authentication/emundus_oauth2_cci/language/fr-FR/fr-FR.plg_authentication_emundus_oauth2_cci.ini
  plugins/fabrik_form/php/scripts/emundus-IMT_confirm_post.php
  plugins/user/emundus_registration_email/emundus_registration_email.php
  plugins/user/emundus_registration_email/emundus_registration_email.xml
Labels: bugfix

#595 Changed CPF code and added support for system messages in HESAM message module.
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  modules/mod_emundus_message_notification/helper.php
Labels: bugfix, enhancement

#596 Minor bugfixes linked to HESAM message system now having system messages.
  components/com_emundus/models/messages.php
  modules/mod_emundus_message_notification/helper.php
  modules/mod_emundus_message_notification/mod_emundus_message_notification.php
  modules/mod_emundus_message_notification/tmpl/default.php
  modules/mod_emundus_message_notification/tmpl/dropdown_menu.php
Labels: bugfix

#597 Modified POST vars because user info sent in message was backwards.
  components/com_emundus/controllers/cifre.php
Labels: bugfix

#600 Added HESAM recap email plugin.
  components/com_emundus/controllers/messages.php
  components/com_emundus/models/cifre.php
  plugins/fabrik_cron/emundushesamrecap/emundushesamrecap.php
  plugins/fabrik_cron/emundushesamrecap/emundushesamrecap.xml
  plugins/fabrik_cron/emundushesamrecap/forms/fields.xml
  plugins/fabrik_cron/emundushesamrecap/forms/index.html
  plugins/fabrik_cron/emundushesamrecap/index.html
  plugins/fabrik_cron/emundushesamrecap/language/en-GB/en-GB.plg_fabrik_cron_emundushesamrecap.ini
  plugins/fabrik_cron/emundushesamrecap/language/en-GB/en-GB.plg_fabrik_cron_emundushesamrecap.sys.ini
  plugins/fabrik_cron/emundushesamrecap/language/fr-FR/fr-FR.plg_fabrik_cron_emundushesamrecap.ini
  plugins/fabrik_cron/emundushesamrecap/language/fr-FR/fr-FR.plg_fabrik_cron_emundushesamrecap.sys.ini
Labels: Plugin, feature

#601 Added HESAM recap email plugin.
  components/com_emundus/controllers/messages.php
  components/com_emundus/models/cifre.php
  plugins/fabrik_cron/emundushesamrecap/emundushesamrecap.php
  plugins/fabrik_cron/emundushesamrecap/emundushesamrecap.xml
  plugins/fabrik_cron/emundushesamrecap/forms/fields.xml
  plugins/fabrik_cron/emundushesamrecap/forms/index.html
  plugins/fabrik_cron/emundushesamrecap/index.html
  plugins/fabrik_cron/emundushesamrecap/language/en-GB/en-GB.plg_fabrik_cron_emundushesamrecap.ini
  plugins/fabrik_cron/emundushesamrecap/language/en-GB/en-GB.plg_fabrik_cron_emundushesamrecap.sys.ini
  plugins/fabrik_cron/emundushesamrecap/language/fr-FR/fr-FR.plg_fabrik_cron_emundushesamrecap.ini
  plugins/fabrik_cron/emundushesamrecap/language/fr-FR/fr-FR.plg_fabrik_cron_emundushesamrecap.sys.ini
Labels: Plugin, feature

#603 Updated module/panel to have lean mode.
  modules/mod_emundus_user_dropdown/tmpl/mobile.php
  modules/mod_emunduspanel/language/en-GB/en-GB.mod_emunduspanel.ini
  modules/mod_emunduspanel/language/fr-FR/fr-FR.mod_emunduspanel.ini
  modules/mod_emunduspanel/mod_emunduspanel.php
  modules/mod_emunduspanel/mod_emunduspanel.xml
  modules/mod_emunduspanel/tmpl/default.php
Labels: Module, feature

#604 Fixed leanmode boolean.
  modules/mod_emunduspanel/mod_emunduspanel.php
Labels: bugfix, patch

#605 Fixed a critical error in module/panel lean mode linked to array parsing.
  modules/mod_emunduspanel/mod_emunduspanel.php
Labels: Module, bugfix
