Repository emundus/v6, pull requests merged in 2019-11, with the labels that each got.

#839 Build 3.9.12/20191107
  administrator/components/com_emundus/logo.png
  components/com_emundus/controllers/admission.php
  components/com_emundus/emundus.php
  components/com_emundus/helpers/access.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  components/com_emundus/models/users.php
  components/com_emundus/views/application/view.raw.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/checklist/view.html.php
  components/com_emundus/views/trombinoscope/tmpl/default.php
  components/com_emundus/views/users/tmpl/adduser.php
  images/logo.png
  media/com_emundus/css/emundus_files.css
  media/com_emundus/js/em_files.js
  modules/mod_emundus_applications/tmpl/esiea.php
  plugins/emundus/aurion_sync_setup_campaigns_excelia/aurion_sync_setup_campaigns_excelia.php
  plugins/emundus/aurion_sync_setup_campaigns_excelia/aurion_sync_setup_campaigns_excelia.xml
  plugins/emundus/aurion_sync_setup_campaigns_excelia/index.html
  plugins/emundus/aurion_sync_setup_programs/aurion_sync_setup_programs.php
  plugins/emundus/aurion_sync_setup_programs/aurion_sync_setup_programs.xml
  plugins/emundus/aurion_sync_setup_programs/index.html
  plugins/emundus/aurion_sync_setup_teaching_unity/aurion_sync_setup_teaching_unity.php
  plugins/emundus/aurion_sync_setup_teaching_unity/aurion_sync_setup_teaching_unity.xml
  plugins/emundus/aurion_sync_setup_teaching_unity/index.html
  plugins/fabrik_cron/aurion/aurion.php
  plugins/fabrik_cron/aurion/aurion.xml
  plugins/fabrik_cron/aurion/files/.gitignore
  plugins/fabrik_cron/aurion/files/index.html
  plugins/fabrik_cron/aurion/forms/fields.xml
  plugins/fabrik_cron/aurion/forms/index.html
  plugins/fabrik_cron/aurion/index.html
  plugins/fabrik_cron/aurion/language/en-GB/en-GB.plg_fabrik_cron_aurion.ini
  plugins/fabrik_cron/aurion/language/en-GB/en-GB.plg_fabrik_cron_aurion.sys.ini
  plugins/fabrik_cron/aurion/language/fr-FR/fr-FR.plg_fabrik_cron_aurion.ini
  plugins/fabrik_cron/aurion/language/fr-FR/fr-FR.plg_fabrik_cron_aurion.sys.ini
  plugins/fabrik_form/php/scripts/emundus-attachment_public.php
  plugins/hikashop/exceliaprice/exceliaprice.php
  plugins/hikashop/exceliaprice/exceliaprice.xml
  plugins/hikashop/exceliaprice/language/en-GB/en-GB.plg_hikashop_exceliaprice.ini
  plugins/hikashop/exceliaprice/language/en-GB/en-GBplg_hikashop_exceliaprice.sys.ini
  plugins/hikashop/exceliaprice/language/fr-FR/fr-FR.plg_hikashop_exceliaprice.ini
  plugins/hikashop/exceliaprice/language/fr-FR/fr-FR.plg_hikashop_exceliaprice.sys.ini
  templates/g5_helium/custom/custom-js.js.dist
  templates/g5_helium/custom/scss/custom.scss.dist
Labels: Plugin, Production, bugfix, imports

#842 Minor bugfixes.
  components/com_emundus/controllers/messages.php
  components/com_emundus/models/application.php
  components/com_emundus/views/users/tmpl/adduser.php
Labels: bugfix

#843 Fixed the nationality stats SQL and readded PHPWord into composer.
  components/com_emundus/models/stats.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: bugfix

#845 Dev
  administrator/components/com_admin/sql/updates/mysql/3.9.12-2019-11-26-em.sql
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  components/com_emundus/models/files.php
  components/com_emundus/views/checklist/view.html.php
  components/com_fabrik/views/form/tmpl/bootstrap/default.php
  components/com_fabrik/views/form/tmpl/bootstrap/default.zip
  libraries/emundus/pdf_evaluationrin100.php
  libraries/emundus/pdf_evaluationrin50.php
  modules/mod_emundus_applications/tmpl/esiea.php
  modules/mod_emundusflow/tmpl/default.php
  modules/mod_emundusflow/tmpl/esiea.php
  plugins/emundus/aurion_sync_setup_campaigns_excelia/aurion_sync_setup_campaigns_excelia.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
  plugins/hikashop/emundus_hikashop/emundus_hikashop.php
  plugins/hikashop/emundus_hikashop/emundus_hikashop.xml
  plugins/hikashop/emundus_hikashop/language/en-GB/en-GB.plg_hikashop_emundus_hikashop.ini
  plugins/hikashop/emundus_hikashop/language/en-GB/en-GBplg_hikashop_emundus_hikashop.sys.ini
  plugins/hikashop/emundus_hikashop/language/fr-FR/fr-FR.plg_hikashop_emundus_hikashop.ini
  plugins/hikashop/emundus_hikashop/language/fr-FR/fr-FR.plg_hikashop_emundus_hikashop.sys.ini
Labels: bugfix, payment

#847 Minor XLS export improvements, a bugfix on socument hiding, and a general improvement of the application model.
  components/com_emundus/controllers/admission.php
  components/com_emundus/controllers/decision.php
  components/com_emundus/controllers/evaluation.php
  components/com_emundus/controllers/files.php
  components/com_emundus/models/application.php
  components/com_emundus/views/application/view.html.php
  components/com_emundus/views/application/view.raw.php
  components/com_emundus/views/checklist/view.html.php
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_send_application/mod_emundus_send_application.php
  modules/mod_emundusflow/mod_emundusflow.php
  plugins/fabrik_form/emunduscompletefilestatuschange/emunduscompletefilestatuschange.php
  plugins/fabrik_form/php/scripts/emundus-PEPITE-isApplicationCompleted.php
  plugins/fabrik_form/php/scripts/emundus-isApplicationCompleted.php
Labels: Exports, bugfix, enhancement
