Repository emundus/v6, pull requests merged in 2019-08, with the labels that each got.

#749 Add limit parameters for getUsers to select all users for delete and …
  components/com_emundus/controllers/users.php
  components/com_emundus/emundus.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/users.php
  components/com_emundus/views/users/tmpl/user.php
Labels: bugfix, users

#752 Removed a display:none; present on the print application button.
  modules/mod_emundus_applications/style/mod_emundus_applications.css
Labels: Design, bugfix

#754 More CSS fixes.
  media/com_emundus/css/emundus_checklist.css
  modules/mod_emundus_user_dropdown/style/mod_emundus_user_dropdown.css
Labels: Design, bugfix

#755 Additionnal fixes to the CSS.
  components/com_fabrik/views/form/tmpl/bootstrap/custom_css.php
Labels: Design, bugfix

#756 Removed !importants in backoffice CSS.
  media/com_emundus/css/emundus.css
  media/com_emundus/css/emundus_checklist.css
  media/com_emundus/css/emundus_files.css
  modules/mod_emundusflow/style/emundus.css
Labels: Design, bugfix

#758 More corrections to unintentional CSS overrides...
  components/com_fabrik/views/form/tmpl/bootstrap/custom_css.php
  media/com_emundus/css/emundus_files.css
Labels: Design, bugfix

#760 Plugin file upload
  plugins/fabrik_element/emundus_fileupload/adaptors/index.html
  plugins/fabrik_element/emundus_fileupload/css/emundus_fileupload.css
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.js
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.php
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.xml
  plugins/fabrik_element/emundus_fileupload/forms/fields.xml
  plugins/fabrik_element/emundus_fileupload/language/fr-FR/fr-FR.plg_fabrik_element_emundus_fileupload.ini
  plugins/fabrik_element/emundus_fileupload/layouts/fabrik-element-emundus_fileupload-form.php
  plugins/fabrik_element/emundus_fileupload/layouts/fabrik-element-emundus_fileupload-qr.php
Labels: Fabrik, Plugin, feature

#762 Added emundus fileupload plugin and minor improvements to CCIRS claroline plugin.
  components/com_fabrik/views/form/tmpl/bootstrap/custom_css.php
  media/com_emundus/css/emundus_files.css
  media/com_emundus/css/reset.css
  plugins/fabrik_element/emundus_fileupload/adaptors/index.html
  plugins/fabrik_element/emundus_fileupload/css/emundus_fileupload.css
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.js
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.php
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.xml
  plugins/fabrik_element/emundus_fileupload/forms/fields.xml
  plugins/fabrik_element/emundus_fileupload/language/fr-FR/fr-FR.plg_fabrik_element_emundus_fileupload.ini
  plugins/fabrik_element/emundus_fileupload/layouts/fabrik-element-emundus_fileupload-form.php
  plugins/fabrik_element/emundus_fileupload/layouts/fabrik-element-emundus_fileupload-qr.php
  plugins/fabrik_form/php/scripts/emundus-ccirs-campaign-multi.php
Labels: Fabrik, Plugin, feature

#763 Greatly improved tag system in emundusreferent plugin.
  plugins/fabrik_form/emundusreferentletter/emundusreferentletter.php
Labels: Plugin, enhancement

#765 Minor bugfixes.
  administrator/templates/isis/images/joomla.png
  administrator/templates/isis/images/logo.png
  media/com_emundus/js/em_files.js
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.php
  plugins/fabrik_form/juseremundus/juseremundus.php
Labels: bugfix

#769 eMundus flow module now has options allowing it to show and hide different parts of the form.
  modules/mod_emundusflow/language/en-GB/en-GB.mod_emundusflow.ini
  modules/mod_emundusflow/language/fr-FR/fr-FR.mod_emundusflow.ini
  modules/mod_emundusflow/mod_emundusflow.php
  modules/mod_emundusflow/mod_emundusflow.xml
  modules/mod_emundusflow/tmpl/default.php
  templates/g5_helium/html/com_users/profile/edit.php
Labels: Module, bugfix, feature

#770 Added email template to password reset email.
  components/com_emundus/controllers/users.php
  components/com_emundus/emundus.php
  components/com_emundus/models/users.php
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.js
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.php
  plugins/fabrik_element/emundus_fileupload/language/en-GB/en-GB.plg_fabrik_element_field.ini
  plugins/fabrik_element/emundus_fileupload/language/fr-FR/fr-FR.plg_fabrik_element_emundus_fileupload.ini
  templates/g5_helium/html/com_users/reset/complete.php
  templates/g5_helium/html/com_users/reset/confirm.php
  templates/g5_helium/html/com_users/reset/default.php
  templates/g5_helium/html/com_users/reset/default.xml
  templates/g5_helium/html/com_users/reset/index.html
Labels: emails, feature
