Repository emundus/v6, pull requests merged in 2019-04, with the labels that each got.

#633 Improved plugin/pushToAPI and CCIConnect OAuth2 plugin.
  components/com_fabrik/views/list/tmpl/cci_companys/default.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.xml
  plugins/fabrik_form/emunduspushfiletoapi/emunduspushfiletoapi.php
  plugins/system/oauth2/oauth2.php
  plugins/user/emundus/emundus.php
Labels: Plugin, bugfix, enhancement

#634 Minor bug fixes, improvements to CCIRS TNS, and other QOL improvements.
  components/com_emundus/models/files.php
  components/com_emundus/views/evaluation/tmpl/data.php
  components/com_emundus/views/evaluation/view.raw.php
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  plugins/fabrik_form/emunduspushfiletoapi/emunduspushfiletoapi.php
  plugins/fabrik_form/php/scripts/emundus-CCIRS_TNS-create-assign-company.php
Labels: Module, Plugin, Quality of life, bugfix

#635 Build 3.9.4/20190410
  components/com_emundus/models/files.php
  components/com_emundus/models/programme.php
  components/com_emundus/views/evaluation/tmpl/data.php
  components/com_emundus/views/evaluation/view.raw.php
  components/com_emundus/views/programme/tmpl/default.php
  components/com_emundus/views/programme/tmpl/default.xml
  components/com_emundus/views/programme/view.html.php
  components/com_fabrik/views/list/tmpl/cci_companys/default.php
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.php
  plugins/authentication/emundus_oauth2_cci/emundus_oauth2_cci.xml
  plugins/fabrik_form/emunduspushfiletoapi/emunduspushfiletoapi.php
  plugins/fabrik_form/emunduspushfiletoapi/forms/fields.xml
  plugins/fabrik_form/emunduspushfiletoapi/language/en-GB/en-GB.plg_fabrik_form_emunduspushfiletoapi.ini
  plugins/fabrik_form/emunduspushfiletoapi/language/fr-FR/fr-FR.plg_fabrik_form_emunduspushfiletoapi.ini
  plugins/fabrik_form/php/scripts/emundus-CCIRS_TNS-create-assign-company.php
  plugins/system/oauth2/oauth2.php
  plugins/user/emundus/emundus.php
Labels: Module, Plugin, Quality of life, bugfix

#640 Fixed errors on campaign module.
  modules/mod_emundus_campaign/language/en-GB/en-GB.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/language/fr-FR/fr-FR.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/tmpl/default_g5.php
Labels: bugfix

#641 Fixed a terrible terrible thing...
  modules/mod_emundus_campaign/tmpl/default_g5.php
Labels: bugfix, embarassing

#642 Fixed module/campaigns params and ItemIDs
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundus_campaign/mod_emundus_campaign.xml
  modules/mod_emundus_campaign/tmpl/default_g5.php
Labels: Module, bugfix

#643 Hesam search engine performance improvements
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.sys.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.sys.ini
  components/com_emundus/models/files.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/checklist/tmpl/default.xml
  components/com_emundus/views/checklist/view.html.php
  components/com_emundus/views/files/tmpl/access.php
  components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
  components/com_fabrik/views/details/tmpl/search_engine/default.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
  libraries/emundus/pdf.php
  modules/mod_emundus_campaign/tmpl/default_g5.php
  modules/mod_emundus_user_dropdown/mod_emundus_user_dropdown.php
  modules/mod_emundus_user_dropdown/tmpl/mobile.php
  modules/mod_emundusflow/tmpl/default.php
  modules/mod_emundusflow/tmpl/esiea.php
  modules/mod_emundusmenu/mod_emundusmenu.php
  plugins/fabrik_form/php/scripts/emundus-sync_actions.php
  templates/g5_helium/html/com_users/login/default_login.php
  templates/g5_helium/html/com_users/profile/edit.php
Labels: search engine

#646 Updated logout URL to support sites with a /path/ in the main URL.
  modules/mod_emundus_user_dropdown/tmpl/default.php
  modules/mod_emundus_user_dropdown/tmpl/list.php
  modules/mod_emundus_user_dropdown/tmpl/mobile.php
  modules/mod_emundus_user_dropdown/tmpl/nostyle.php
Labels: bugfix

#647 Fixed more bugs linked to sites in a repo.
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/message/tmpl/default.php
  plugins/user/emundus/emundus.php
Labels: bugfix

#648 More improvements to the campaign module and absolute URLs.
  modules/mod_emundus_campaign/helper.php
  modules/mod_emundus_campaign/tmpl/default_g5.php
  plugins/fabrik_form/emunduscampaign/emunduscampaign.php
Labels: Module, bugfix

#650 Improved LDAP user addition frontend structure.
  administrator/components/com_admin/sql/updates/mysql/3.9.5-2019-04-18-em.sql
  components/com_emundus/controllers/files.php
  components/com_emundus/emundus.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/views/users/tmpl/adduser.php
  media/com_emundus/js/em_files.js
  modules/mod_emundus_campaign/language/fr-FR/fr-FR.mod_emundus_campaign.ini
Labels: Design, enhancement, users

#653 Accidentally inverted if
  components/com_emundus/views/users/tmpl/adduser.php
Labels: embarassing

#659 Reworked module/applications to have better links for both sending and opening a file.
  components/com_emundus/controller.php
  components/com_emundus/models/application.php
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_applications/tmpl/esiea.php
  modules/mod_emundus_applications/tmpl/hesam.php
  modules/mod_emundus_applications/tmpl/nanomed.php
  modules/mod_emundus_applications/tmpl/pse.php
  modules/mod_emundus_applications/tmpl/ti.php
Labels: Module, bugfix

#661 Minor bugfixes to module/campaign, evaluator view, and letter exports.
  components/com_emundus/controllers/files.php
  components/com_emundus/models/evaluation.php
  modules/mod_emundus_campaign/mod_emundus_campaign.php
  modules/mod_emundus_campaign/tmpl/default_g5.php
Labels: Evaluation, Exports, Module, bugfix

#662 Minor bugfixes.
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/views/application/view.raw.php
  media/com_emundus/js/em_files.js
Labels: bugfix

#663 Used some super tricky manual overriding of the composer files to get PHPOffice to work.
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: Exports, bugfix, dependencies

#664 Fixed deleting attachments in backoffice from non-absolute site.
  components/com_emundus/views/application/tmpl/attachment.php
Labels: bugfix

#667 Hesam improvments, Backend translation of Fabrik elements in exports, Bugfixes.
  components/com_emundus/controllers/evaluation.php
  components/com_emundus/helpers/files.php
  components/com_emundus/helpers/filters.php
  components/com_emundus/models/admission.php
  components/com_emundus/models/application.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_emundus/views/programme/tmpl/default.php
  components/com_emundus/views/trombinoscope/tmpl/default.php
  components/com_emundus/views/users/tmpl/adduser.php
  components/com_emundus/views/users/tmpl/showgrouprights.php
  components/com_fabrik/views/details/tmpl/hesam_pdf_export/custom_css.php
  components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
  media/com_emundus/js/em_files.js
  modules/mod_emundus_campaign/tmpl/default_g5.php
  modules/mod_emundus_graphs/mod_emundus_graphs.php
Labels: Exports, bugfix, search engine, translation

#668 Fixed export tmpl to show table labels when exploding labels without dashes in their name.
  components/com_emundus/views/export_select_columns/tmpl/default.php
  components/com_emundus/views/export_select_columns/view.raw.php
Labels: Exports, bugfix

#669 HESAM - updates
  components/com_emundus/controllers/messages.php
  components/com_emundus/models/users.php
  components/com_fabrik/views/list/tmpl/search_engine/default.php
Labels: Production, users

#671 Removed content before dash on fabrik form title.
  components/com_fabrik/views/form/tmpl/bootstrap/default.php
Labels: Fabrik

#672 Removed content before dash in bootstrap_tabs tmpl as well.
  components/com_fabrik/views/form/tmpl/bootstrap_tabs/default.php
Labels: Fabrik
