Repository emundus/v6, pull requests merged in 2019-06, with the labels that each got.

#656 Add name or type of file in email sent to candidate and update style
  .idea/workspace.xml
  components/com_emundus/controllers/messages.php
  components/com_emundus/views/message/tmpl/default.php
  media/com_emundus/css/emundus_files.css
Labels: emails

#697 Added some minor fixes and code style enhancements to the ESIEA custom PDF code.
  libraries/emundus/pdf_esiea-1a.php
Labels: Exports

#698 Changed custom ESIEA pdf to be used for reinscriptions programme and not first year only.
  libraries/emundus/pdf_esiea-r.php
Labels: Admission, Exports, bugfix

#699 Multiplied the ESIEA reinscriptions PDFs to handle the new programme organization.
  libraries/emundus/pdf_esiea-1ar.php
  libraries/emundus/pdf_esiea-2ar.php
  libraries/emundus/pdf_esiea-3ar.php
  libraries/emundus/pdf_esiea-4ar.php
Labels: Admission, Exports

#702 Fix css problem on the checkbox to select all files, the alignment of…
  media/com_emundus/css/emundus_files.css
Labels: Design, bugfix

#701 Remove the class modal-open to the body which add an overflow hidden
  media/com_emundus/js/em_files.js
Labels: Design, bugfix

#700 Fix the problem of null value category
  administrator/components/com_admin/sql/updates/mysql/3.9.8-2019-06-25-em.sql
  components/com_emundus/views/application/tmpl/attachment.php
Labels: bugfix

#703 Style bugfixes and other general bugfixes/improvements for ESIEA.
  administrator/components/com_admin/sql/updates/mysql/3.9.8-2019-06-25-em.sql
  components/com_emundus/models/application.php
  components/com_emundus/views/application/tmpl/attachment.php
  libraries/emundus/pdf_esiea-1ar.php
  libraries/emundus/pdf_esiea-2ar.php
  libraries/emundus/pdf_esiea-3ar.php
  libraries/emundus/pdf_esiea-4ar.php
  media/com_emundus/css/emundus_files.css
  media/com_emundus/js/em_files.js
  plugins/fabrik_form/emundusdocusign/emundusdocusign.php
  plugins/fabrik_form/php/scripts/emundus-csv_import.php
Labels: Design, bugfix, imports, payment

#706 Esiea Docusign improvements and CCI enhancements
  administrator/components/com_admin/sql/updates/mysql/3.9.1-2019-02-05-em.sql
  components/com_emundus/models/files.php
  components/com_emundus/views/email/tmpl/expert.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
  libraries/emundus/pdf_esiea-1ar.php
  libraries/emundus/pdf_esiea-2ar.php
  libraries/emundus/pdf_esiea-3ar.php
  libraries/emundus/pdf_esiea-4ar.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
Labels: Exports, GesCOF, enhancement, search engine

#708 Improvements to file select checkbox, as well as some style and JS bugs.
  components/com_emundus/views/decision/tmpl/data.php
  components/com_emundus/views/evaluation/tmpl/data.php
  components/com_emundus/views/files/tmpl/menuactions.php
  components/com_emundus/views/users/tmpl/user.php
  media/com_emundus/css/emundus_files.css
  media/com_emundus/js/em_files.js
  media/com_emundus/js/em_user.js
  modules/mod_emundus_book_interview/language/fr-FR/fr-FR.mod_emundus_book_interview.ini
Labels: Design, bugfix

#710 Added a param to hide empty field in form exports and fixed some tiny bugs.
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  libraries/emundus/pdf_emploi.php
  libraries/emundus/pdf_evaluationpiu.php
  plugins/fabrik_form/php/scripts/emundus-EMPLOI_new_job.php
  plugins/fabrik_list/su_copy_fiche_emplois/su_copy_fiche_emplois.php
Labels: Exports, bugfix
