Repository emundus/v6, pull requests merged in 2019-10, with the labels that each got.

#802 Anonymization, applications module improvements, CSS, and bugfixes.
  administrator/components/com_admin/sql/updates/mysql/3.9.12-2019-09-27-em.sql
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/controller.php
  components/com_emundus/controllers/admission.php
  components/com_emundus/controllers/decision.php
  components/com_emundus/controllers/evaluation.php
  components/com_emundus/controllers/files.php
  components/com_emundus/helpers/access.php
  components/com_emundus/helpers/files.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  components/com_emundus/models/decision.php
  components/com_emundus/models/files.php
  components/com_emundus/models/groups.php
  components/com_emundus/models/messages.php
  components/com_emundus/models/users.php
  components/com_emundus/views/admission/tmpl/data.php
  components/com_emundus/views/application/tmpl/attachment.php
  components/com_emundus/views/application/tmpl/synthesis.php
  components/com_emundus/views/application/view.raw.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/decision/tmpl/data.php
  components/com_emundus/views/decision/view.raw.php
  components/com_emundus/views/evaluation/tmpl/data.php
  components/com_emundus/views/export_select_columns/tmpl/programme.php
  components/com_emundus/views/export_select_columns/view.raw.php
  components/com_emundus/views/files/tmpl/data.php
  components/com_emundus/views/message/tmpl/default.php
  components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
  components/com_fabrik/views/list/tmpl/label_with_description/default.php
  libraries/emundus/pdf.php
  media/com_emundus/css/emundus_files.css
  media/com_emundus/css/reset.css
  modules/mod_emundus_applications/language/en-GB/en-GB.mod_emundus_applications.ini
  modules/mod_emundus_applications/language/fr-FR/fr-FR.mod_emundus_applications.ini
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_applications/mod_emundus_applications.xml
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  modules/mod_emundus_user_dropdown/mod_emundus_user_dropdown.php
  modules/mod_emundus_user_dropdown/mod_emundus_user_dropdown.xml
  modules/mod_emundus_user_dropdown/tmpl/default.php
  modules/mod_emundus_user_dropdown/tmpl/nostyle.php
  modules/mod_emundusflow/language/en-GB/en-GB.mod_emundusflow.ini
  modules/mod_emundusflow/language/fr-FR/fr-FR.mod_emundusflow.ini
  modules/mod_emundusflow/mod_emundusflow.php
  modules/mod_emundusflow/mod_emundusflow.xml
  modules/mod_emundusflow/tmpl/default.php
  plugins/user/emundus/emundus.php
  plugins/user/emundus_registration_email/emundus_registration_email.php
  templates/g5_helium/html/com_users/login/style/com_users_login.css
  templates/g5_helium/templateDetails.xml
Labels: Design, Exports, Module, bugfix, users

#820 Staging
  libraries/emundus/pdf.php
  modules/mod_emundus_user_dropdown/tmpl/default.php
Labels: embarassing

#823 Bug fixes and other improvements.
  components/com_emundus/controllers/users.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  components/com_emundus/models/users.php
  components/com_emundus/views/application/tmpl/attachment.php
  media/com_emundus/css/emundus_checklist.css
  modules/mod_emundusflow/tmpl/default.php
  plugins/fabrik_cron/migal_ftp/migal_ftp.php
  plugins/fabrik_element/emundus_fileupload/language/en-GB/en-GB.plg_fabrik_element_emundus_fileupload.ini
  plugins/fabrik_form/emunduscampaign/emunduscampaign.php
  plugins/fabrik_form/emundusreferentletter/emundusreferentletter.php
  plugins/fabrik_form/php/scripts/emundus-campaign.php
  plugins/fabrik_form/php/scripts/emundus-referent_letter.php
  templates/g5_helium/custom/scss/custom.scss.dist
Labels: bugfix

#825 Corrected the trombinoscope header/footer implementations, and corrected some styiling issues.
  components/com_emundus/controllers/trombinoscope.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/programme.php
  components/com_emundus/models/trombinoscope.php
  components/com_emundus/views/trombinoscope/tmpl/default.php
  components/com_emundus/views/trombinoscope/view.html.php
  media/com_emundus/css/emundus_files.css
  media/com_emundus/css/reset.css
  modules/mod_emundus_campaign/mod_emundus_campaign.php
Labels: Design, Exports, bugfix

#826 Build 3.9.12/20191008
  components/com_emundus/controllers/trombinoscope.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/programme.php
  components/com_emundus/models/trombinoscope.php
  components/com_emundus/views/trombinoscope/tmpl/default.php
  components/com_emundus/views/trombinoscope/view.html.php
  media/com_emundus/css/emundus_files.css
  media/com_emundus/css/reset.css
  modules/mod_emundus_campaign/mod_emundus_campaign.php
Labels: Design, Production, bugfix, enhancement

#827 XLS exports and trombinocope export bug fixes.
  components/com_emundus/controllers/files.php
  components/com_emundus/controllers/trombinoscope.php
Labels: Exports, bugfix

#828 Build 3.9.12/20191009
  components/com_emundus/controllers/files.php
  components/com_emundus/controllers/trombinoscope.php
Labels: Exports, Production, bugfix

#831 New PDF templates models.
  administrator/templates/isis/images/joomla.png
  administrator/templates/isis/images/logo.png
  libraries/emundus/pdf_communs.php
  libraries/emundus/pdf_covoiturage.php
  libraries/emundus/pdf_glisse-urbaine.php
  modules/mod_emundus_applications/style/mod_emundus_applications.css
Labels: Exports

#830 Build 3.9.12/20191010
  administrator/templates/isis/images/joomla.png
  administrator/templates/isis/images/logo.png
  components/com_emundus/models/application.php
  libraries/emundus/pdf_communs.php
  libraries/emundus/pdf_covoiturage.php
  libraries/emundus/pdf_glisse-urbaine.php
  modules/mod_emundus_applications/style/mod_emundus_applications.css
  modules/mod_emundus_graphs/tmpl/default.php
Labels: Exports, bugfix, dashboard

#833 Build 3.9.12/20191011
  media/com_emundus/js/em_files.js
Labels: Production, bugfix

#834 Fix application module link to send user to the first form
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  templates/g5_helium/custom/scss/custom.scss.dist
Labels: Design, bugfix

#836 Bugfixes and improvments to admission workflow.
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.sys.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.sys.ini
  components/com_emundus/models/application.php
  components/com_emundus/models/checklist.php
  components/com_emundus/models/emails.php
  components/com_emundus/models/files.php
  components/com_emundus/views/application/view.raw.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/checklist/tmpl/default.xml
  components/com_emundus/views/checklist/view.html.php
  modules/mod_emundus_applications/tmpl/esiea.php
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.php
  plugins/fabrik_element/emundusreferent/css/emundusreferent.css
  plugins/fabrik_element/emundusreferent/emundusreferent-min.js
  plugins/fabrik_element/emundusreferent/emundusreferent.js
  plugins/fabrik_element/emundusreferent/emundusreferent.php
  plugins/fabrik_element/emundusreferent/language/en-GB/en-GB.plg_fabrik_element_emundusreferent.ini
  plugins/fabrik_element/emundusreferent/language/fr-FR/fr-FR.plg_fabrik_element_emundusreferent.ini
  plugins/fabrik_form/emundussetprofile/emundussetprofile.php
  plugins/fabrik_form/emundussetprofile/forms/fields.xml
  templates/g5_helium/custom/scss/custom.scss.dist
Labels: Admission, Fabrik, Plugin, bugfix

#837 Newly created views now have automatic ACL creation.
  administrator/components/com_emundus/models/actions.php
  administrator/components/com_emundus/views/actions/view.html.php
  components/com_emundus/controllers/groups.php
  components/com_emundus/helpers/files.php
  components/com_emundus/models/users.php
  components/com_emundus/views/users/view.html.php
  plugins/fabrik_element/emundusreferent/css/emundusreferent.css
  plugins/fabrik_element/emundusreferent/emundusreferent.php
Labels: Design, bugfix, groups

#835 Build 3.9.12/20191014
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.sys.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.sys.ini
  administrator/components/com_emundus/models/actions.php
  administrator/components/com_emundus/views/actions/view.html.php
  components/com_emundus/controllers/groups.php
  components/com_emundus/helpers/files.php
  components/com_emundus/models/application.php
  components/com_emundus/models/checklist.php
  components/com_emundus/models/emails.php
  components/com_emundus/models/files.php
  components/com_emundus/models/users.php
  components/com_emundus/views/application/view.raw.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/checklist/tmpl/default.xml
  components/com_emundus/views/checklist/view.html.php
  components/com_emundus/views/users/view.html.php
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.php
  plugins/fabrik_element/emundusreferent/css/emundusreferent.css
  plugins/fabrik_element/emundusreferent/emundusreferent-min.js
  plugins/fabrik_element/emundusreferent/emundusreferent.js
  plugins/fabrik_element/emundusreferent/emundusreferent.php
  plugins/fabrik_element/emundusreferent/language/en-GB/en-GB.plg_fabrik_element_emundusreferent.ini
  plugins/fabrik_element/emundusreferent/language/fr-FR/fr-FR.plg_fabrik_element_emundusreferent.ini
  plugins/fabrik_form/emundussetprofile/emundussetprofile.php
  plugins/fabrik_form/emundussetprofile/forms/fields.xml
  templates/g5_helium/custom/scss/custom.scss.dist
Labels: Production, bugfix
