Repository emundus/v6, pull requests merged in 2020-04, with the labels that each got.

#905 Further refining of Addpipe webhook, bugfixes.
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/controller.php
  components/com_emundus/controllers/webhook.php
  components/com_emundus/emundus.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/files.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/checklist/view.raw.php
  media/com_emundus/js/em_files.js
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_applications/tmpl/ccirs.php
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  modules/mod_emundus_applications/tmpl/hesam.php
  modules/mod_emundus_applications/tmpl/nanomed.php
  modules/mod_emundus_applications/tmpl/pse.php
  modules/mod_emundus_applications/tmpl/ti.php
  plugins/fabrik_form/emundusisevaluationconfirmed/emundusisevaluationconfirmed.php
  plugins/fabrik_form/php/scripts/emundus-csv_import.php
Labels: bugfix, feature

#906 Build 6.9.15/20200406
  administrator/components/com_emundus/config.xml
  administrator/components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  administrator/components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  administrator/language/fr-FR/fr-FR.ini
  components/com_emundus/controller.php
  components/com_emundus/controllers/files.php
  components/com_emundus/controllers/webhook.php
  components/com_emundus/emundus.php
  components/com_emundus/helpers/files.php
  components/com_emundus/language/en-GB/en-GB.com_emundus.ini
  components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
  components/com_emundus/models/application.php
  components/com_emundus/models/checklist.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/files.php
  components/com_emundus/views/checklist/tmpl/default.php
  components/com_emundus/views/checklist/view.raw.php
  components/com_emundus/views/programme/tmpl/default.php
  components/com_emundus/views/webhook/index.html
  components/com_emundus/views/webhook/tmpl/default.php
  components/com_emundus/views/webhook/tmpl/default.xml
  components/com_emundus/views/webhook/tmpl/index.html
  components/com_emundus/views/webhook/view.html.php
  components/com_emundus/views/webhook/view.raw.php
  language/fr-FR/fr-FR.ini
  media/com_emundus/js/em_files.js
  modules/mod_emundus_applications/mod_emundus_applications.php
  modules/mod_emundus_applications/tmpl/ccirs.php
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  modules/mod_emundus_applications/tmpl/hesam.php
  modules/mod_emundus_applications/tmpl/nanomed.php
  modules/mod_emundus_applications/tmpl/pse.php
  modules/mod_emundus_applications/tmpl/ti.php
  modules/mod_emundus_campaign/language/en-GB/en-GB.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/language/fr-FR/fr-FR.mod_emundus_campaign.ini
  modules/mod_emundus_campaign/tmpl/default_g5.php
  modules/mod_emundus_campaign/tmpl/nantes.php
  modules/mod_emundus_custom/helper.php
  plugins/fabrik_form/emundusisevaluationconfirmed/emundusisevaluationconfirmed.php
  plugins/fabrik_form/emundusredirect/emundusredirect.php
  plugins/fabrik_form/php/scripts/emundus-attachment.php
  plugins/fabrik_form/php/scripts/emundus-attachment_public.php
  plugins/fabrik_form/php/scripts/emundus-csv_import.php
Labels: Production, bugfix, enhancement, feature, imports, release

#909 Update ATTACHMENT_PROGRESS and APPLICATION_PROGRESS tags
  administrator/components/com_admin/sql/updates/mysql/3.9.16-2020-04-08.sql
Labels: bugfix

#910 Fixed issue where require once was pointing to the component constant.
  components/com_emundus/models/application.php
Labels: bugfix

#911 Build 6.9.16/20200408R
  components/com_emundus/models/application.php
Labels: Production, bugfix

#912 Build 6.9.15/20200408R2
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
Labels: bugfix, embarassing

#914 Dev
  administrator/components/com_admin/sql/updates/mysql/3.9.16-2020-04-08-em.sql
  components/com_emundus/controllers/messages.php
  components/com_emundus/models/application.php
  components/com_emundus/models/files.php
  components/com_emundus/views/application/view.raw.php
  libraries/emundus/pdf_admission.php
  libraries/emundus/pdf_decision.php
  libraries/emundus/pdf_evaluation.php
  modules/mod_emundus_applications/tmpl/default.php
  modules/mod_emundus_applications/tmpl/esiea.php
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.php
  plugins/fabrik_form/emundusisapplicationsent/emundusisapplicationsent.php
  plugins/fabrik_form/emundusisevaluatedbyme/emundusisevaluatedbyme.php
  plugins/fabrik_form/php/scripts/emundus-csv_import.php
Labels: bugfix

#915 Build 6.9.16/20200414
  administrator/components/com_admin/sql/updates/mysql/3.9.16-2020-04-08-em.sql
  components/com_emundus/controllers/messages.php
  components/com_emundus/models/application.php
  components/com_emundus/models/files.php
  components/com_emundus/views/application/view.raw.php
  libraries/emundus/pdf_admission.php
  libraries/emundus/pdf_decision.php
  libraries/emundus/pdf_evaluation.php
  plugins/fabrik_element/emundus_fileupload/emundus_fileupload.php
  plugins/fabrik_form/emundusisapplicationsent/emundusisapplicationsent.php
  plugins/fabrik_form/emundusisevaluatedbyme/emundusisevaluatedbyme.php
  plugins/fabrik_form/php/scripts/emundus-csv_import.php
Labels: Production, bugfix

#917 PATCH/20200415
  components/com_emundus/models/users.php
Labels: bugfix

#919 PATCH/20200421
  components/com_emundus/views/checklist/tmpl/default.php
Labels: Uploads, bugfix

#921 Merge vanilla CSS changes into dev branch.
  components/com_emundus/views/programme/tmpl/default.php
  components/com_fabrik/views/form/tmpl/bootstrap/custom_css.php
  language/fr-FR/fr-FR.com_users.ini
  media/com_emundus/css/emundus.css
  media/com_emundus/css/emundus_programme.css
  modules/mod_emundus_applications/style/mod_emundus_applications.css
  modules/mod_emundus_campaign/css/mod_emundus_campaign.css
  modules/mod_emundus_campaign/tmpl/default.php
  modules/mod_emundus_campaign/tmpl/default_g5.php
  modules/mod_emunduspanel/language/en-GB/en-GB.mod_emunduspanel.ini
  modules/mod_emunduspanel/language/fr-FR/fr-FR.mod_emunduspanel.ini
  modules/mod_emunduspanel/style/emundus.css
  modules/mod_emunduspanel/tmpl/default.php
  templates/g5_helium/custom/scss/custom.scss.dist
  templates/g5_helium/html/com_users/login/default_login.php
  templates/g5_helium/html/com_users/login/style/com_users_login.css
  templates/g5_helium/html/com_users/profile/style/com_users_profile.css
  templates/g5_helium/html/com_users/reset/complete.php
  templates/g5_helium/html/com_users/reset/confirm.php
  templates/g5_helium/html/com_users/reset/default.php
  templates/g5_helium/html/com_users/reset/style/com_users_reset.css
  templates/g5_helium/html/mod_login/default.php
  templates/g5_helium/html/mod_login/style/mod_login.css
Labels: Design

#920 Added ability to add a NOT IN prefilter for tags (by adding ! in fron…
  components/com_emundus/helpers/files.php
  components/com_emundus/models/admission.php
  components/com_emundus/models/decision.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/files.php
Labels: feature, filters

#924 Fixed case where tag NOT IN filters were not being set if session did…
  components/com_emundus/models/admission.php
  components/com_emundus/models/decision.php
  components/com_emundus/models/evaluation.php
  components/com_emundus/models/files.php
Labels: bugfix
