Repository emundus/v6, pull requests merged in 2020-06, with the labels that each got.

#946 em_files get fnum in action menu fix
  media/com_emundus/js/em_files.js
Labels: bugfix, javascript

#944 Feature/mod login
  administrator/components/com_admin/sql/updates/mysql/3.9.19-2020-06-17-em.sql
  modules/mod_emundus_user_dropdown/helper.php
  modules/mod_emundus_user_dropdown/language/en-GB/en-GB.mod_emundus_user_dropdown.ini
  modules/mod_emundus_user_dropdown/language/fr-FR/fr-FR.mod_emundus_user_dropdown.ini
  modules/mod_emundus_user_dropdown/mod_emundus_user_dropdown.php
  modules/mod_emundus_user_dropdown/mod_emundus_user_dropdown.xml
  modules/mod_emundus_user_dropdown/style/mod_emundus_user_dropdown.css
  modules/mod_emundus_user_dropdown/tmpl/default.php
  modules/mod_emundus_user_dropdown/tmpl/list.php
  modules/mod_emundus_user_dropdown/tmpl/mobile.php
  modules/mod_emundus_user_dropdown/tmpl/nostyle.php
Labels: Module, Quality of life, feature

#950 Fixed issue with users created without a profile not having profile 1000.
  plugins/user/emundus/emundus.php
Labels: Production, bugfix, patch, users

#954 Hotfix/fix all files selection
  media/com_emundus/js/em_files.js
Labels: bugfix
